import { findPassage, passageLevels, type Passage, type PassageLevel } from "@/app/passages";
import type { StoryQuiz } from "@/app/stories";

/* The stories children get as their assignment: proper storybook tales,
   written to be enjoyed, in the spirit of the funny, warm, larger-than-life
   books children love: a narrator with a voice, characters with silly
   names, comic disasters, a twist, and a heart at the end. All original.

   Kept apart from the Guided Reading passages (timed read-alouds). Each is
   one page of flowing storybook prose: a scene-setting opening, a curious
   discovery, connected sentences, a line of speech and a magical turn at
   the end. About 70 words at Starter, 85 in Year 1, 95 in Year 2 and
   100-110 from Year 3, with sentence length and vocabulary stepping up.

   The Lexile figures are estimates within each level's band. */

function A(
  id: string,
  title: string,
  emoji: string,
  lexile: number,
  text: string,
  question: string,
  options: [string, string][],
): Passage {
  const quiz: StoryQuiz = {
    question,
    options: options.map(([e, l]) => ({ emoji: e, label: l })),
    answer: 0,
  };
  return { id, title, emoji, lexile, text, quiz };
}

const STARTER: Passage[] = [
  A("as-st-01", "The Red Egg", "🥚", 50, "One sunny morning, a little red hen found a big red egg in her nest. It was hot, and it went tap, tap, tap. The hen sat on it and waited. Then, with a loud crack, out popped a tiny dragon! It could not cluck, but it could puff little clouds of smoke. The hen gave it a big hug. “You are my chick now,” she said, and the little dragon puffed with joy.", "What pops out of the egg?", [["🐉", "A dragon"], ["🐤", "A chick"], ["🐍", "A snake"]]),
  A("as-st-02", "Pig and the Bubble Bath", "🐷", 50, "One hot day, Pig rolled in the mud until he was a big brown blob. Mum Pig put him in the tub and added a pink bottle of bubbles. The bubbles got bigger and bigger. Then a big bubble lifted Pig up, up, up into the sky! He floated over the farm and waved at the hens. At last, the bubble went pop, and Pig fell down with a splat, right back in the mud!", "Where did Pig land at the end?", [["🟤", "Back in the mud"], ["🛁", "In the tub"], ["🛏️", "In bed"]]),
  A("as-st-03", "Ten Hens in a Van", "🚐", 50, "Ten hens had a little red van, and every day they went for a drive. One day, a sly fox stopped the van. “Let me in,” he said, licking his lips. The hens looked at each other and let him in. Then all ten hens began to peck. Peck, peck, peck! The fox jumped out and ran off as fast as he could. The hens cheered and drove home for tea.", "Who pecked the fox?", [["🐔", "Ten hens"], ["🐶", "A dog"], ["🐱", "A cat"]]),
  A("as-st-04", "Ted Can Fly", "🧸", 50, "Every night, when Sam was fast asleep, Ted the teddy got up. He put on his little red cape and jumped onto the bed. Then up, up, up he went, out of the window and into the sky! Ted zipped past the moon and waved at the stars. When the sun began to rise, he flew back home and hopped into bed. In the morning, Sam hugged Ted and had no idea.", "What can Ted do at night?", [["🦸", "Fly"], ["🏊", "Swim"], ["🍳", "Cook"]]),
  A("as-st-05", "The Bug Who Was King", "👑", 50, "One morning, a little bug found a gold ring by the pond. He put it on his head and grinned. “I am the king of the pond!” he said. The fish nodded, the frog bowed, and the duck gave a loud quack. Then the rain came, plop, plop, plop, and the ring filled up with water. The little king sat in it and had a bath. “This is fit for a king,” he said.", "What did the bug put on his head?", [["💍", "A gold ring"], ["🎩", "A hat"], ["🍃", "A leaf"]]),
  A("as-st-06", "Kit and the Magic Mat", "🪄", 50, "Kit the cat had a red mat, but it was not just any mat. When Kit sat on it, it went up, up, up into the sky! First, they flew to the sun. “Too hot!” said Kit. Next, they flew to the moon. “Too cold!” said Kit. At last, the mat flew back home and landed on his bed. Kit curled up on it and said, “Just right.”", "What can the magic mat do?", [["🪄", "Fly"], ["🎵", "Sing"], ["🍽️", "Cook"]]),
  A("as-st-07", "The Big Bone", "🦴", 50, "One day at the beach, Rex the dog began to dig in the sand. He dug and dug until he found a bone, a big, big bone! Rex tugged it with his teeth. Then, all of a sudden, the bone began to move. It was a dinosaur! “Hello,” it said with a yawn. “Can I have a bun?” Sam gave the dinosaur a bun, but Rex just wanted his bone back.", "What did Rex dig up?", [["🦖", "A dinosaur"], ["🪙", "A coin"], ["🐚", "A shell"]]),
  A("as-st-08", "The Duck Who Did Not Quack", "🦆", 50, "On a log by the pond sat a little duck. All the other ducks said quack, but this duck opened her beak and said, “Moo!” The ducks got such a fright that a frog fell into the pond. A cow ran up to look. “Is that my mum?” she asked. The little duck went red and gave a shy grin. “Sorry,” she said. “I have a cold.”", "What did the duck say?", [["🐮", "Moo"], ["🦆", "Quack"], ["🐶", "Woof"]]),
  A("as-st-09", "The Pot That Did Not Stop", "🍲", 50, "Gran had a magic pot. When she said, “Cook, pot, cook!” it filled up with hot soup. When she said, “Stop, pot, stop!” it stopped. One day, Gran went out, and Sam felt hungry. “Cook, pot, cook!” he said. The soup filled the pot, then the hut, then the whole street! Sam forgot the magic words. At last, Gran came back and called, “Stop, pot, stop!”", "What does the magic pot make?", [["🍲", "Soup"], ["🍪", "Biscuits"], ["🧃", "Juice"]]),
  A("as-st-10", "Big Bad Bob", "🐻", 50, "In a deep, dark wood lived Bob, a big, bad bear. Every morning, he stood on a rock and let out a huge roar. “I am big and bad!” he said. “I am not scared of anything!” Then one day, a tiny bird landed on his nose and sang, “Tweet, tweet!” Bob gave a yelp and ran all the way home to his den. Big, bad Bob was scared of birds!", "What made Bob run off?", [["🐦", "A bird"], ["🐍", "A snake"], ["🦁", "A lion"]]),
];

const YEAR1: Passage[] = [
  A("as-y1-01", "The Grumpiest Goat in the World", "🐐", 300, "On a busy farm lived Gertie, the grumpiest goat in the world. When the sun came out, she said, “Too hot!” When the rain came down, she said, “Too wet!” One spring morning, a tiny lamb bounced across the field. Boing! Boing! It hopped right up to Gertie and gave her a big, woolly hug. Gertie went pink, then red. Slowly, the corner of her mouth began to curl. The hens gasped and fell off their perch. For the very first time, Gertie was smiling!", "Who made Gertie smile?", [["🐑", "A tiny lamb"], ["🐔", "A hen"], ["👨‍🌾", "The farmer"]]),
  A("as-y1-02", "Sir Snorebert", "🛡️", 330, "Long ago, in a tall stone castle, lived a knight called Sir Snorebert. He was very brave, but he could never stay awake. One stormy night, a dragon swooped over the castle walls. “Wake up!” shouted the king. Sir Snorebert just rolled over and snored. It was the loudest snore anyone had ever heard! It shook the towers and blew the crown off the king's head. The dragon was so frightened that it flew far away. The king gave Sir Snorebert a medal, but he was still asleep.", "How did Sir Snorebert scare the dragon away?", [["😴", "With a loud snore"], ["⚔️", "With his sword"], ["🐴", "On his horse"]]),
  A("as-y1-03", "The Mermaid's Magic Shell", "🧜", 360, "Deep under the sea lived Mira, a little mermaid with a magic shell. Whenever she sang into it, the waves began to dance. One morning, a greedy crab snatched the shell and scuttled away. Mira swam after him, past the coral and the sleepy turtles. The crab hid in a dark cave. So Mira sat outside and sang a soft lullaby. The crab yawned once, then twice, and fell fast asleep. Mira picked up her shell and swam home, and that night, the waves danced until dawn.", "How did Mira get her shell back?", [["🎵", "She sang a lullaby"], ["🗡️", "She fought the crab"], ["🎁", "She gave the crab a present"]]),
  A("as-y1-04", "Mr Muddle's Magic Socks", "🧦", 380, "One windy Tuesday, Mr Muddle walked into a strange little shop and bought some purple socks with yellow spots. “They are magic,” whispered the shopkeeper with a wink. Mr Muddle laughed and put them on. At once, his feet began to dance! They danced him out of the door, down the road and into the town square. Tap, tap, twirl! People clapped, and a dog joined in. By teatime, Mr Muddle was very tired. He locked the socks in a drawer, but at night, he can still hear them tapping.", "What did the magic socks make Mr Muddle do?", [["💃", "Dance"], ["🏃", "Run"], ["😴", "Sleep"]]),
  A("as-y1-05", "The Cat Who Thought She Was a Dog", "🐱", 400, "In a little blue house lived a cat called Mimi. She had soft whiskers and a long, swishy tail, but Mimi thought she was a dog! She fetched sticks, chased the postman and went for walks on a lead. People stared and giggled. Then, one sunny day, a big dog called Bruno moved in next door. Bruno curled up on the windowsill and began to purr. Mimi blinked in surprise. Bruno thought he was a cat! So they swapped jobs, and everyone was much happier.", "What did Bruno think he was?", [["🐱", "A cat"], ["🐶", "A dog"], ["🐟", "A fish"]]),
  A("as-y1-06", "The Giant's Tiny Problem", "🦶", 420, "High in the hills lived Gus, a giant as tall as a tree. Gus had a tiny problem: a little mouse lived in his shoe! Every time Gus took a step, the mouse squeaked. Squeak, squeak! The other giants laughed so much that the mountains shook. Gus did not want to hurt the mouse. So he built it a tiny wooden house and put it in his top pocket. Now the mouse rides with Gus wherever he goes, and it has the best view in the land.", "Where did the mouse live at first?", [["👟", "In Gus's shoe"], ["🏠", "In a house"], ["🎩", "In a hat"]]),
  A("as-y1-07", "The Tooth Fairy's Day Off", "🧚", 440, "One night, Lily put her wobbly tooth under her pillow and fell asleep. But the Tooth Fairy had a terrible cold, so she sent her little brother, Dennis. Dennis had never done the job before. He flew in through the window, bumped into the lamp and splashed into the goldfish bowl. By the time he was dry, he had forgotten why he had come. He took the tooth and left a sock! The next morning, Lily wrote a note: “Dear Tooth Fairy, I think there has been a mix-up.”", "What did Dennis leave under the pillow?", [["🧦", "A sock"], ["🪙", "A coin"], ["🍪", "A biscuit"]]),
  A("as-y1-08", "Sang Kancil and the Crocodiles", "🐊", 460, "Long ago, in a green jungle, lived Sang Kancil, a small mouse deer who was very clever. One hot day, he saw sweet fruit on the other side of the river. But the river was full of hungry crocodiles! “The King wants to count you,” Kancil called. “Please line up across the river!” The crocodiles lined up, nose to tail. Kancil hopped from back to back, counting, “One, two, three...” When he reached the other side, he laughed. “Thank you for the bridge!”", "How did Kancil cross the river?", [["🐊", "On the crocodiles' backs"], ["🛶", "In a boat"], ["🏊", "He swam"]]),
  A("as-y1-09", "The Wizard's Wobbly Wand", "🧙", 490, "In a crooked tower lived Wizard Wilf and his clever cat, Pickle. Wilf had a very wobbly wand. When he tried to make a cake, he made a snake! When he tried to make it rain, he made a train! Wilf sat down and sighed. Pickle looked closely at the wand and smiled. “You are holding it upside down,” she said. Wilf turned it round and waved it once more. Poof! A huge chocolate cake appeared, and Wilf and Pickle ate every crumb.", "What did Wilf make when he tried to make a cake?", [["🐍", "A snake"], ["🚂", "A train"], ["🌧️", "Rain"]]),
  A("as-y1-10", "The Moon Wants a Holiday", "🌙", 520, "One night, the Moon felt very tired. “I need a holiday,” she said. So she floated down to the beach, put on her sunglasses and ate an ice cream. But the sky was very dark without her. Owls bumped into trees, and cats fell off walls. A little girl called Nora walked down to the beach. “Please come back,” she said. “We miss you.” The Moon felt a warm glow inside. She floated back up to the sky, and now she takes just one holiday a month.", "Who asked the Moon to come back?", [["👧", "Nora"], ["🦉", "An owl"], ["🐱", "A cat"]]),
];

const YEAR2: Passage[] = [
  A("as-y2-01", "The Day the Teacher Turned Into a Frog", "🐸", 480, "On a grey Monday morning, Mr Bunting, the strictest teacher at Puddleford School, took a sip of his tea. Someone had swapped the sugar for a strange green powder! Puff! In a cloud of smoke, he turned into a small frog wearing tiny glasses. Class 2B cheered. They ate crisps for breakfast and painted the ceiling. But by home time, the classroom felt far too quiet. Priya picked up the frog and gave him a gentle kiss to say sorry. Puff! Mr Bunting was back, with pond weed in his hair, and for the very first time, he laughed.", "What did Priya do to turn the frog back?", [["💋", "Gave it a kiss"], ["🍵", "Gave it tea"], ["📚", "Read it a book"]]),
  A("as-y2-02", "Nenek's Magic Wok", "🥘", 500, "In a sleepy kampung by the river lived Nenek and her magic wok. Whatever she cooked in it made people kind. One stormy evening, a grumpy giant stomped into the village, shouting and stamping. Everyone ran inside and hid. But Nenek calmly lit her stove and cooked a steaming plate of nasi lemak. She carried it out to the giant. He sniffed it, then took one bite. Slowly, his frown melted away. “Thank you,” he whispered. Now, every Saturday, the giant helps Nenek carry her shopping home.", "What did the magic wok make people?", [["😊", "Kind"], ["😴", "Sleepy"], ["💪", "Strong"]]),
  A("as-y2-03", "Kevin the Talking Rock", "🪨", 510, "One quiet afternoon, Ruby was digging in the garden when she found a smooth grey rock. As she brushed off the soil, the rock gave an enormous yawn. “Good morning,” it said. “My name is Kevin.” Ruby nearly dropped him! Kevin explained that he was a thousand years old and knew every story in the world. Every night after that, he told Ruby a new tale about dragons, pirates and faraway kingdoms. When her friends visited, Kevin stayed perfectly silent. But as soon as they left, he winked.", "What did Kevin tell Ruby every night?", [["📖", "A story"], ["🎵", "A song"], ["⭐", "A wish"]]),
  A("as-y2-04", "Captain Cutlass and the Very Small Ship", "🏴‍☠️", 530, "Out on the stormy sea sailed Captain Cutlass, the fiercest pirate of them all. There was just one problem: his ship was really a bathtub with a sail. Other sailors laughed so hard that they nearly fell overboard. One wild night, a huge wave sank a great ship called the Golden Goose. Its sailors could not swim! Captain Cutlass rowed bravely through the waves and pulled all seventeen of them into his bath. He took them safely home. They offered him a grand new ship, but he gave it back. “Too big,” he said.", "What was Captain Cutlass's ship really?", [["🛁", "A bathtub"], ["🚢", "A huge ship"], ["🛶", "A canoe"]]),
  A("as-y2-05", "The Girl Who Could Talk to Clouds", "☁️", 550, "On a hot summer's day, Ella sat on a hill and talked to the clouds. She was the only person in the village who could. The farmers' fields were dry and dusty, and the crops were drooping. “Please, clouds,” Ella called, “we need rain!” But the clouds were too busy racing each other across the sky. So Ella had an idea. “I'll race you!” she shouted, and she ran down the hill as fast as she could. The clouds raced after her and bumped together. Crash! Rain poured down on the fields.", "How did Ella make the clouds bump together?", [["🏃", "She raced them"], ["🎶", "She sang to them"], ["🪁", "She flew a kite"]]),
  A("as-y2-06", "Uncle Bernard's Bouncing Bed", "🛏️", 560, "One starry night, Uncle Bernard climbed into his brand-new bed. The label said it was the bounciest bed ever made, but Uncle Bernard never read labels. He took a running jump. BOING! He shot straight up through the roof in his pyjamas, still holding his teddy. He bounced over the church, over the school and right across the river. “Lovely evening!” he called to Mrs Patel. At last, he floated back down through the hole in the roof and landed on his bed. In the morning, he said he had dreamed of flying.", "Where did Uncle Bernard land at the end?", [["🛏️", "Back on his bed"], ["🌊", "In the river"], ["⛪", "On the church"]]),
  A("as-y2-07", "The Shy Dragon", "🐉", 580, "High on a snowy mountain lived Fizz, a dragon who was terribly shy. Whenever she blushed, puffs of smoke came out of her ears, and the villagers ran away screaming. One freezing winter, the village ran out of firewood. A brave boy called Tomas climbed all the way up to her cave. “Please help us,” he said, shivering. “We're freezing.” Fizz took a deep breath and gently blew warm air over the village. The snow melted, and the houses grew cosy and warm. Everyone cheered. Fizz blushed, but this time she didn't mind.", "What happened when Fizz blushed?", [["💨", "Smoke came out of her ears"], ["🔥", "She breathed fire"], ["🌈", "She turned rainbow"]]),
  A("as-y2-08", "Mr Plum's Unusual Shop", "🏪", 590, "At the end of a cobbled street stood a shop that sold things you didn't know you needed. One rainy afternoon, Leo stepped inside. A tall man with a purple moustache handed him a small brass key. “What does it open?” asked Leo. Mr Plum just smiled. All week, Leo tried the key in every lock, but nothing opened. Then, on Friday, his little sister got locked in the bathroom! Leo tried the key, and with a click, the door swung open. When he ran back to say thank you, the shop had vanished.", "What did the brass key open?", [["🚪", "The bathroom door"], ["🍪", "The biscuit tin"], ["🚲", "His bike lock"]]),
  A("as-y2-09", "The Great Hamster Escape", "🐹", 600, "Every night, when the classroom was dark and quiet, Nibbles the hamster practised his great escape. On Friday, he picked the lock of his cage with a sunflower seed. He slid down the table leg, scurried past the bookshelf and dived into Miss Hart's handbag. Inside, he found mints and half a sandwich. He ate until his cheeks were round, then curled up and fell asleep. On Monday morning, Miss Hart reached for a pen and screamed! Out rolled Nibbles, with a mint stuck to his ear. He was already planning his next adventure.", "Where did Nibbles hide?", [["👜", "In the teacher's handbag"], ["📚", "Behind the books"], ["🎒", "In a school bag"]]),
  A("as-y2-10", "Granny Goes to Space", "🚀", 610, "Granny Joan was ninety-two years old, and she had always dreamed of going to space. “You're far too old!” everyone said. So, one quiet evening, she built a rocket in the garden shed out of a dustbin and a giant firework. She put on her best cardigan and a goldfish bowl for a helmet. Five, four, three, two, one... WHOOSH! She zoomed past the clouds, looped around the Moon and had a cup of tea with an astronaut. Then she floated gently home. “Too old?” she said. “Next week, I'm going to Mars!”", "What did Granny use as a helmet?", [["🐠", "A goldfish bowl"], ["🪣", "A bucket"], ["🎩", "A top hat"]]),
];

const YEAR3: Passage[] = [
  A("as-y3-01", "The Boy Who Swallowed a Thunderstorm", "⛈️", 680, "On a wild, rainy afternoon, Felix Fennimore ran outside with his mouth wide open to catch the raindrops. Instead, he swallowed a small, grumbling thundercloud! After that, whenever Felix got cross, his tummy rumbled with thunder, and whenever he ate sprouts, rain drizzled out of his ears. Then, one summer, a terrible drought came. The fields turned brown, and the village well dried up. Felix marched into the dusty fields, thought about every annoying thing that had ever happened to him, and let out an enormous roar. Out burst the thunderstorm, and rain poured down at last.", "How did Felix make the rain come?", [["😠", "He got very cross and roared"], ["💃", "He did a rain dance"], ["💧", "He used a hose"]]),
  A("as-y3-02", "Detective Dumpling and the Missing Mangoes", "🥭", 690, "In the sleepy village of Kampung Bunga, there lived an eight-year-old detective called Dumpling. One morning, Pak Ali came running down the lane. “Someone has stolen my mangoes!” he cried. Detective Dumpling grabbed her magnifying glass and set to work. Mrs Lim's goat had an alibi, and the postman was allergic to mangoes. Then she spotted a trail of mango peel leading from the bus stop all the way to the edge of the jungle. She looked up. There, in a tall tree, sat a very fat, very happy monkey. It gave an enormous burp. The case was solved!", "Who stole the mangoes?", [["🐒", "A monkey"], ["🐐", "Mrs Lim's goat"], ["📮", "The postman"]]),
  A("as-y3-03", "The Boy Who Shrank", "🔍", 700, "During a science lesson one Tuesday, Barnaby sneezed so hard that he shrank to the size of a pea. Nobody noticed. Curious, he climbed onto the teacher's desk, dodged a gigantic pencil and rode a friendly ladybird across the classroom. From up high, he spotted the class goldfish trapped behind a book that had fallen into its tank. Using all his tiny strength, Barnaby pushed the book aside. The grateful goldfish blew a shimmering bubble that floated over to him. Pop! In a flash, Barnaby was back to his normal size, just in time for lunch.", "Who helped Barnaby return to his normal size?", [["🐟", "The goldfish"], ["🐞", "A ladybird"], ["👩‍🏫", "The teacher"]]),
  A("as-y3-04", "The Unicorn Who Hated Rainbows", "🦄", 710, "In the sparkling land of Glimmerdale, every unicorn adored rainbows, except Clementine. She thought rainbows were far too bright, and she much preferred grey clouds and muddy puddles. The other unicorns thought she was very strange indeed. Then, one dark afternoon, a terrible storm swept across the sky and swallowed every rainbow. The unicorns trembled, but Clementine galloped happily into the gloom. Splashing through puddle after puddle, she followed a faint shimmer until she found the lost rainbows hiding underneath a cloud. Gently, she led them home, and the sky glowed brighter than ever before.", "Where were the lost rainbows hiding?", [["☁️", "Underneath a cloud"], ["🌊", "In the sea"], ["🏔️", "On a mountain"]]),
  A("as-y3-05", "The Library at the Bottom of the Sea", "🐙", 720, "While snorkelling one summer morning, Marina noticed a light flickering far below the waves. Curious, she took a deep breath and dived down, past swaying seaweed and silver fish, until she reached a stone door half buried in the sand. Above it, in letters covered with barnacles, were the words: THE SUNKEN LIBRARY. Inside, an elderly octopus wearing four pairs of spectacles was stamping books with all eight arms. Marina spent the whole afternoon reading pirate diaries and whale atlases. Before she left, she borrowed one silver book. If you open it today, you can still hear the sea.", "Who was the librarian?", [["🐙", "An octopus"], ["🦀", "A crab"], ["🐋", "A whale"]]),
  A("as-y3-06", "Mrs Mangle's Magnificent Moustache", "👵", 730, "In the village of Little Snoring, the baker, Mrs Mangle, suddenly began to grow a moustache. Nobody knew why. By Friday, it was so long that she had to tuck it into her apron. Then came the Great Village Bake-Off. Mrs Mangle carried out the tallest cake anyone had ever seen, wobbling like a jelly. Just as she set it down, the top layer began to slide! Everyone gasped. Quick as a flash, she flicked her magnificent moustache underneath and held it perfectly in place. She won first prize, of course. “You never know when you'll need one,” she said.", "How did Mrs Mangle save her cake?", [["👨", "With her moustache"], ["🥄", "With a big spoon"], ["🧤", "With oven gloves"]]),
  A("as-y3-07", "The Robot Who Wanted to Be a Chicken", "🤖", 740, "In a busy laboratory full of whirring machines, Professor Gearbox built Unit X-9000, the cleverest robot in the world. It could speak forty languages and build a bridge before breakfast. But Unit X-9000 had a secret wish: it wanted to be a chicken. One morning, it walked into the vegetable patch, sat down and said, “Bawk.” So the professor took it to a farm. There, it learned to strut, peck and fluff up the feathers it had made from tin foil. It never laid an egg, but it built the hens the best henhouse ever, complete with a disco ball.", "What did the robot design for the hens?", [["🏠", "The best henhouse in the world"], ["🌉", "A bridge"], ["🚀", "A rocket"]]),
  A("as-y3-08", "The Night the Toys Went on Strike", "🧸", 760, "Every night, when Maisie fell asleep, her toys came to life. Lately, however, they were not happy. Maisie had left her teddy, Captain Buttons, out in the rain and drawn a moustache on her favourite doll. So, one moonlit night, the toys held a secret meeting under the bed and went on strike. The next morning, Maisie's shelves were empty. She searched everywhere until she found them in the garden shed, holding tiny signs that said: WE WANT RESPECT. Maisie felt ashamed. She said sorry to every toy and carried them home. That night, Captain Buttons winked.", "Where did Maisie find her toys?", [["🛖", "In the garden shed"], ["🛏️", "Under the bed"], ["📦", "In the attic"]]),
  A("as-y3-09", "Granny's Great Gorilla Mix-Up", "🦍", 780, "When Granny Pearl ordered a fluffy brown rug online, she clicked the wrong button. The next morning, a delivery van brought an enormous box with air holes. Inside was a fluffy brown gorilla called Gordon! Granny was very short-sighted, so she laid him in front of the fire and stood on him to reach the top shelf. Gordon was far too polite to complain. When her grandson came to visit, the rug gave a huge yawn, and he screamed. But Granny refused to let Gordon go. “He does the gardening,” she said, “and he's an excellent listener.”", "What did Granny Pearl think Gordon was?", [["🟫", "A rug"], ["🧸", "A teddy"], ["🐻", "A bear"]]),
  A("as-y3-10", "The Kite That Flew Away With Mr Tan", "🪁", 800, "Every Sunday for fifty years, Mr Tan had flown kites on the beach. This year, he built his masterpiece: a rainbow kite as big as a bus. “Too big,” warned his wife from her deckchair. Mr Tan just smiled and let it go. Whoosh! The wind caught the kite, and suddenly his feet lifted off the sand. Up he floated, over the waves and past a fishing boat. A family of monkeys on an island threw a banana at him, which he caught and ate. An hour later, he drifted gently back down. “Too big?” asked his wife. “Perhaps,” he admitted.", "What did the monkeys throw at Mr Tan?", [["🍌", "A banana"], ["🥥", "A coconut"], ["🪨", "A stone"]]),
];

const YEAR4: Passage[] = [
  A("as-y4-01", "The Headmaster Who Was Secretly a Wizard", "🧙", 790, "Dr Hushworth, the headmaster of St Bartholomew's School, hated noise more than anything. Then, during a silent assembly one Monday, Amira noticed something peculiar: a tiny silver wand poking out of his sleeve. That afternoon, curiosity got the better of her. She tiptoed down the corridor and peeped through his keyhole. Inside, Dr Hushworth waved the wand, and a pile of homework transformed into a flock of fluttering paper birds. Amira gasped. Instantly, the headmaster spun round and opened the door. For a long moment, he stared at her. “Can you keep a secret?” he asked. Now, every Friday, he teaches Amira magic.", "What did the headmaster turn the homework into?", [["🐦", "Paper birds"], ["🐸", "Frogs"], ["🍰", "A cake"]]),
  A("as-y4-02", "The Secret Diary of a Very Nervous Lighthouse", "🗼", 800, "On a lonely rock at the edge of the sea stood Lumi, a lighthouse who was secretly afraid of the dark. Every evening, as the sun sank, her lamp trembled. During storms, she squeezed her light shut and pretended to be a very tall tree. Then, one foggy night, she spotted a little fishing boat heading straight for the rocks. A girl in a yellow raincoat was steering it, unable to see the danger. Lumi was shaking, but she thought: how frightened must that girl be? So she took a deep breath and shone brighter than ever before. The boat turned just in time.", "What was Lumi the lighthouse scared of?", [["🌑", "The dark"], ["🌊", "Big waves"], ["🐦", "Seagulls"]]),
  A("as-y4-03", "The Grandad Who Lived in a Teapot", "🫖", 810, "Oliver's grandad was only five centimetres tall, and he lived inside a teapot on the kitchen shelf. Nobody else in the family knew. Each evening, after dinner, Oliver lifted the lid, and Grandad told him thrilling stories about sailing teacup boats across the sink and battling fearsome spoons. One morning, however, Mum reached for the teapot to make a fresh brew. Oliver gasped. He dived across the kitchen, knocking over a chair, and caught the teapot just in time. From that day on, the family has drunk coffee instead, and Grandad is extremely grateful.", "Where did Grandad live?", [["🫖", "In a teapot"], ["☕", "In a teacup"], ["🏠", "In a dolls' house"]]),
  A("as-y4-04", "The Ghost Who Was Afraid of Children", "👻", 820, "For three hundred years, the ghost of Lady Wimbledon had terrified every visitor to Grimthorpe Castle. She rattled chains, moaned in the chimneys and made the portraits' eyes follow people around the room. Then, one autumn, a family with five fearless children moved in. When she rattled her chains, they made a swing out of them. When she floated past carrying her own head, little Hattie asked to hold it. Lady Wimbledon was horrified. Finally, one stormy night, Hattie handed her a book. “Please read us a story,” she said. “You have the perfect spooky voice.” Now Lady Wimbledon reads bedtime stories every night.", "What did the children ask Lady Wimbledon to do?", [["📖", "Read them a story"], ["⛓️", "Rattle her chains"], ["🏰", "Leave the castle"]]),
  A("as-y4-05", "The Inventor of Useless Things", "💡", 830, "Professor Ida Bloom invented things that nobody needed, such as umbrellas for ducks and a sock matcher that ate socks. The whole town laughed at her. Then, one spring, it rained for eleven days without stopping. The river burst its banks, the streets became canals, and the water pumps broke down. In desperation, the mayor paddled a canoe to her bedroom window. “Can you help us?” he begged. Professor Bloom thought for a moment. Then she switched her sock matcher from SOCKS to WATER. All night long, it slurped and gurgled. By morning, the streets were completely dry, and nobody ever laughed at her again.", "What did the Sock Matcher do in the flood?", [["💧", "It sucked up the water"], ["🧦", "It ate socks"], ["🍲", "It made soup"]]),
  A("as-y4-06", "The Night Market Mystery", "🏮", 840, "Every Wednesday, the car park behind Siti's flat turned into a glittering pasar malam, full of lights and delicious smells. But one week, at exactly nine o'clock, every light flickered out, and Auntie Rose's pisang goreng vanished. The next week, a pot of laksa disappeared. People whispered that a ghost was to blame. Determined to solve the mystery, Siti hid under a stall with a torch. When the lights went out, she switched it on and saw a monitor lizard carrying away a tray of banana fritters. She followed it to a drain, where six hungry babies were waiting. The thief was simply a mother doing her shopping.", "Who was stealing the food?", [["🦎", "A mother monitor lizard"], ["👻", "A ghost"], ["👦", "Teenagers"]]),
  A("as-y4-07", "The Boy Who Could Talk to Pigeons", "🐦", 850, "On his tenth birthday, Sam accidentally swallowed a feather and woke up able to understand pigeons. Unfortunately, pigeons never stopped arguing about crumbs. Then, one morning, the mayor's beloved dog went missing, and the whole city searched for days. On his way to school, Sam overheard two pigeons gossiping on a lamp post. “He's stuck in a drainpipe by the river,” said one. Sam raced to the river, and there, wedged in a pipe, was the dog. The mayor offered Sam any reward he wanted. Sam asked for only one thing: a bag of bread for the pigeons. Now they bow whenever he passes.", "Where was the missing dog?", [["🌉", "In a drainpipe by the river"], ["🏞️", "In the park"], ["🏠", "On a roof"]]),
  A("as-y4-08", "The Supermarket at Midnight", "🛒", 860, "At midnight, when the doors of Bumbleton's Supermarket were locked, the food came alive. The bananas held races down aisle three, the tins of soup sang in harmony, and the jellies wobbled to the music. One night, however, a mischievous mouse sneaked in through a crack and began nibbling the cheese. Immediately, the vegetables sprang into action. The carrots charged in a line, the peas rolled like marbles, and the potatoes formed a wall to trap him. By morning, the mouse had been politely escorted outside, and every item was neatly back on its shelf, as if nothing had happened.", "Who chased the mouse?", [["🥕", "The vegetables"], ["🍌", "The bananas"], ["🥫", "The tins of soup"]]),
  A("as-y4-09", "The Elephant Who Forgot", "🐘", 860, "Everyone knows that elephants never forget, which is why Mabel was so embarrassed. She forgot absolutely everything, even where her trunk was. Then came a long, scorching drought. The rivers dried up, and old Grandmother Tembo could no longer remember the way to the secret spring. The herd wandered in circles, growing weaker every day. But because Mabel never remembered anything, she had always looked carefully at everything. She had noticed weaver birds flying north each morning and returning with wet feathers. “Follow the birds!” she trumpeted. The herd followed her over the hills, and there, sparkling in a ring of fig trees, was the spring.", "What helped Mabel find the spring?", [["🐦", "She followed the birds"], ["🗺️", "She used a map"], ["🧠", "She remembered the way"]]),
  A("as-y4-10", "The Toaster That Granted Wishes", "🍞", 870, "When Leo's family bought a second-hand toaster from a dusty market stall, they had no idea it was enchanted. Every slice of toast it produced granted one wish. At breakfast, Leo wished for a puppy, and a fluffy one appeared instantly, licking butter from his fingers. His sister wished for snow, and soon the kitchen was filled with swirling snowflakes. Everyone laughed with delight. Then Dad, who was still half asleep, mumbled that he wished for some peace and quiet. The toaster gave a long sigh, popped out one final golden slice and never granted another wish again.", "What appeared when Leo made his wish?", [["🐶", "A puppy"], ["❄️", "Snow"], ["🍰", "A cake"]]),
];

const YEAR5: Passage[] = [
  A("as-y5-01", "The Boy Who Was Allergic to Adventure", "🗺️", 900, "Horace Plimpton was genuinely allergic to adventure: anything exciting made him break out in purple spots. So he lived a careful life of plain toast and beige jumpers. Then, one wet Thursday, his great-aunt left him a battered trunk containing a map and a note: “The cure is at the X.” Horace hesitated, then set off, sneezing furiously. He was chased by geese, lost in a hedge maze and nearly arrested on a royal barge. At last, he reached the X on a lonely hilltop. There was no treasure, only a bench carved with six words: “The cure is to keep going.” His spots faded completely.", "What was the cure for Horace's allergy?", [["🚶", "To keep going"], ["💊", "A special medicine"], ["💰", "Finding treasure"]]),
  A("as-y5-02", "The Substitute Teacher From the Year 3000", "🛸", 910, "The substitute teacher who arrived at Hollybrook Primary that Monday was decidedly unusual. Ms Zyx wore silver boots, solved long division by blinking at it and seemed utterly astonished by pencils. At lunchtime, she ate her yoghurt, pot and all. By Wednesday, Kofi had worked it out. “You're from the future,” he whispered. She sighed and admitted that she was a historian from the year 3000, studying a real classroom. “In my time, machines entertain everyone constantly,” she explained, “so nobody is ever bored, and nobody imagines anything new.” On Friday, she vanished, leaving a note: “Thank you for the boredom.”", "Why did Ms Zyx visit the past?", [["📚", "To study a real classroom"], ["🍦", "To eat yoghurt"], ["🔭", "To see the Sun"]]),
  A("as-y5-03", "The Durian Tree That Wouldn't Share", "🌳", 920, "At the top of a hill in Kampung Seri grew an ancient durian tree that produced the most magnificent fruit in Malaysia. Unfortunately, it belonged to Encik Kamal, the stingiest man in the state. He surrounded it with fences and refused to share a single durian. Then, one year, the tree stopped fruiting altogether. “Perhaps it's lonely,” suggested little Nurul. That night, sitting alone beneath its bare branches, Encik Kamal finally understood. The next morning, the fences had vanished, and a hand-painted sign read: EVERYONE WELCOME. Within a week, the branches were so heavy with durians that they had to be propped up.", "What made the durian tree fruit again?", [["🤝", "Sharing it with everyone"], ["🧪", "Expensive powder"], ["📜", "A lawyer's letter"]]),
  A("as-y5-04", "The Spelling Bee That Buzzed", "🐝", 930, "Agatha Grimwhistle was the finest speller at Thistlebottom Primary, which was precisely why the real Spelling Bee chose her. It was a tiny golden bee that could buzz any correctly spelled word into existence. “Spell carefully,” it warned. Agatha concentrated hard and spelled “butterfly”, and a shimmering cloud of butterflies burst from her pencil. Her classmates gasped. Then Freddie snatched the pencil and spelled “dinosaur” wrongly. With a pop, a very confused creature appeared in the middle of the classroom, wearing a pink tutu. Agatha grabbed the pencil, corrected the spelling, and the creature became a magnificent, slightly embarrassed dinosaur.", "What happened when Agatha spelled “butterfly”?", [["🦋", "Butterflies appeared"], ["🐝", "The bee flew away"], ["✏️", "Her pencil broke"]]),
  A("as-y5-05", "The Last Dragon in Kuala Lumpur", "🐉", 940, "High on a skyscraper in Kuala Lumpur lived Seri Naga, a secret dragon known only to a girl named Mei Ling. Every Sunday, Mei Ling climbed to the roof with teh tarik and curry puffs, and the dragon told her stories about ancient rainforests. “Where are the other dragons?” Mei Ling asked one day. “When the forests shrink,” Seri Naga replied sadly, “dragons fall asleep.” Determined to help, Mei Ling started a club called the Dragon Keepers, and every member planted a tree. When the half-millionth tree was planted, deep in the rainforest, an ancient dragon opened one enormous golden eye. The dragons were waking up.", "What did members of the Dragon Keepers have to do?", [["🌱", "Plant a tree"], ["🐉", "Find a dragon"], ["🍵", "Make teh tarik"]]),
  A("as-y5-06", "The Sweet Shop Owner Who Hated Children", "🍬", 950, "Mr Grimsby owned the most wonderful sweet shop in town, yet he despised children. He painted his door the colour of cold porridge, and his parrot screeched, “Hurry up!” at every customer. One snowy evening, just before closing, a small girl with holes in her shoes placed a single coin on the counter. “It's my brother's birthday, and he's poorly,” she said. Something deep inside Mr Grimsby's chest gave a creak. Silently, he filled a paper bag with sweets until it would not close, then pushed the coin back. The next morning, his door was bright yellow, and a new sign read: FREE SAMPLES ON FRIDAYS.", "What did Mr Grimsby give the girl?", [["🍭", "A bag full of sweets, and her coin back"], ["🧥", "A new coat"], ["🦜", "His parrot"]]),
  A("as-y5-07", "The World's Worst Superhero", "🦸", 960, "On his eleventh birthday, Archie Nutbrown discovered that he had superpowers, but they were utterly hopeless. He could fly only two centimetres off the ground, and his X-ray vision worked on nothing but sandwiches. Then, during a school trip, a gang of thieves stole the museum's priceless diamond. The police searched every bag and pocket, but the diamond had vanished. Archie squinted at the gang leader's lunchbox. Through the bread, past the ham and a limp lettuce leaf, something glittered. “It's in the sandwich!” he shouted. As the thief ran, Archie hovered just high enough to trip him up. The newspapers called him SANDWICH BOY.", "Where was the diamond hidden?", [["🥪", "In a sandwich"], ["🧥", "In a coat pocket"], ["🎒", "In a school bag"]]),
  A("as-y5-08", "The Girl Who Collected Lost Dreams", "🌙", 970, "Every night, when the town was asleep, Wren crept across the moonlit rooftops with a silver net, collecting the dreams that people forgot by morning. She stored them in glass jars on her windowsill, where they glowed like fireflies. One jar held a very old dream of flying, abandoned by a man named Mr Ellis seventy years earlier. Wren decided it was time to return it. Quietly, she climbed through his window and released the dream beside his pillow. The next morning, the neighbours could hardly believe their eyes: old Mr Ellis was floating above his garden, laughing like a boy.", "What did Wren collect?", [["🌙", "Forgotten dreams"], ["✨", "Fireflies"], ["🧤", "Lost gloves"]]),
  A("as-y5-09", "The Cat Who Ran the Country", "🐈", 980, "Nobody ever discovered how Tiddles, a fat ginger cat with one torn ear, became Prime Minister. Nevertheless, he got straight to work. His first law made afternoon naps compulsory for everyone. His second declared that all cardboard boxes should be left on the floor for sitting in. His third, and most controversial, banned the hoover. Surprisingly, the country changed. People grew calmer and kinder, children built magnificent cardboard rockets in the parks, and families spent weekends together in their gardens. Within a year, the nation was the happiest it had been for a century. Tiddles served one term, then fell asleep in a sunbeam.", "What did Tiddles' first law make compulsory?", [["😴", "Afternoon naps"], ["📦", "Sitting in boxes"], ["🧹", "Hoovering"]]),
  A("as-y5-10", "The Piano That Played at Midnight", "🎹", 990, "Every night at midnight, the old piano in the abandoned Grand Theatre began to play by itself. The townspeople were convinced that it was haunted, so nobody dared to go near. Ottilie, however, was braver than most. One night, she crept through a broken window with a torch and tiptoed towards the stage. Instead of a ghost, she discovered a family of mice dancing across the keys, performing for an audience of fascinated moths. Delighted, Ottilie sat down beside them and played a duet. Now the theatre has reopened, and every Saturday, crowds gather to watch the famous Midnight Mice perform.", "Who was playing the piano?", [["🐭", "A family of mice"], ["👻", "A ghost"], ["🦉", "An owl"]]),
];

const YEAR6: Passage[] = [
  A("as-y6-01", "The Boy Who Sold His Shadow", "🌑", 960, "On an ordinary Wednesday, Jasper sold his shadow to a stranger in a grey suit for one hundred pounds and bought a gleaming bicycle. At first, he barely noticed the difference. Gradually, however, he began forgetting things: his grandmother's laugh, the smell of the sea on summer holidays. Desperate, he searched the town until he found the stranger's shop, its shelves lined with rolled-up shadows. Instead of paying, Jasper stepped out into the blazing sunlight and deliberately remembered every precious detail. With each memory, a faint outline darkened at his feet, until his shadow had grown back completely. The stranger could keep only what people surrendered.", "How did Jasper get his shadow back?", [["🧠", "By holding on to his memories"], ["💰", "By paying the stranger"], ["✂️", "By cutting it out"]]),
  A("as-y6-02", "The Bookshop That Moved", "📚", 970, "Mr Rahman's bookshop on Jalan Merdeka was enchanted: every night, while the city slept, it quietly moved to wherever a reader needed it most. One morning, developers arrived with bulldozers, determined to demolish it for a car park, but they found only an empty plot of land. Puzzled, they scratched their heads and drove away. Meanwhile, the little shop had settled beside a hospital, where a lonely boy was waiting nervously for an operation. Through its window, he glimpsed an extraordinary book about a tiger who became a dentist. He laughed for the first time in weeks. The shop, it seemed, had chosen its next customer.", "Where did the bookshop move to?", [["🏥", "Beside a hospital"], ["🏫", "Beside a school"], ["🏖️", "To the beach"]]),
  A("as-y6-03", "The Unusual Inheritance of Florence Fairbottom", "🏰", 980, "When Florence inherited a crumbling castle on a windswept Scottish island, she also inherited a curse: keep the castle's promise, or it would fall into the sea. Unfortunately, nobody could remember what the promise was. Florence spent the summer exploring secret passages, until she discovered the first Lady of Glenmuckle's diary hidden behind a portrait. Four hundred years earlier, the castle had promised to keep a light burning for anyone lost at sea. That night, Florence climbed all three hundred steps of the highest tower and lit a lantern in the window. By morning, the cracks in the walls had stopped spreading.", "What was the castle's promise?", [["🕯️", "To keep a light burning for anyone lost at sea"], ["💰", "To guard a treasure"], ["🦇", "To protect the bats"]]),
  A("as-y6-04", "The Day Everyone Told the Truth", "🤥", 990, "One March morning, something mysterious in the water supply made every resident of Little Fibbington completely incapable of telling a lie. Chaos erupted immediately. Mr Henderson admitted that his wife's porridge tasted like wallpaper paste, and the mayor confessed that he could not swim. By lunchtime, the whole town was hiding indoors. Yet, by afternoon, something remarkable happened: people began confessing kinder truths. A grumpy postman told an elderly neighbour that her cheerful waving was the best part of his day, and two estranged brothers admitted they had forgotten their argument. Now the town celebrates Truth Day, when everyone says one true, kind thing.", "What good thing happened after the chaos?", [["💬", "People said kind, true things"], ["🏊", "The pool opened"], ["🥣", "The porridge got better"]]),
  A("as-y6-05", "The Lighthouse at the Edge of Time", "⏳", 1000, "On a remote Cornish cliff, old Mrs Penhallow kept a lighthouse that shone not across the sea, but across the centuries. Ships from every age followed its silver beam: Viking longboats, Spanish galleons and, once, a bewildered submarine from the distant future. Each grateful sailor signed her leather logbook before sailing home. When Mrs Penhallow eventually grew too frail to climb the winding stairs, she entrusted the lamp to her granddaughter, Morwenna. On her first night as keeper, Morwenna opened the ancient logbook and froze. There, in faded ink on the very first page, was her own signature, written centuries earlier.", "What did the lighthouse shine across?", [["⏳", "The centuries"], ["🌊", "Only the sea"], ["🏙️", "The city"]]),
  A("as-y6-06", "The Kingdom of Lost Socks", "🧦", 1000, "One rainy Tuesday, Imogen climbed into her family's broken washing machine to retrieve a hairclip and tumbled straight through the drum. She landed in a vast cavern lit by glowing lint, where millions of escaped socks had built a kingdom of woolly towns and silken palaces. Their king, an ancient Christmas sock embroidered with a faded reindeer, declared that they were finally free from smelly trainers. However, Imogen noticed that many socks looked homesick. So she negotiated a treaty: gentle washing, sunshine drying and partners of their choice. Since then, missing socks have decreased dramatically, although a few still take holidays.", "What did Imogen agree with the King of the socks?", [["📜", "A treaty"], ["🧺", "A new washing machine"], ["🎉", "A party"]]),
  A("as-y6-07", "The Clockmaker's Apprentice", "⏰", 1010, "In the crooked town of Ticklethwaite, Master Horologe kept a mysterious clock hidden beneath a dust sheet in the back room of his shop. It had not ticked for a hundred years. When the old clockmaker fell ill one winter, his apprentice, Pip, finally lifted the sheet. The clock's face showed seasons and tides instead of hours, and its brass plate read: THE HEART OF TICKLETHWAITE. Working through the night, Pip cleaned and oiled every rusted gear. As dawn broke, she turned the key. The clock began to tick, and the town transformed: rivers sparkled, gardens bloomed, and upstairs, her master's cough vanished.", "What happened when the great clock ticked again?", [["🌸", "The town came back to life"], ["🌧️", "It began to rain"], ["🔔", "All the bells rang"]]),
  A("as-y6-08", "The Boy Who Painted Doors", "🚪", 1020, "Whatever door Rafael painted on a wall became real. At first, he used his extraordinary gift for mischief, painting escape routes from maths lessons and secret shortcuts to the biscuit cupboard. However, one winter's night, a fire broke out in the old apartment block across the street, trapping the residents on the upper floors. While everyone else ran away, Rafael ran towards the flames. With trembling hands, he dipped his brush into a pot of paint and drew an enormous door on the outside wall. One by one, the frightened residents stepped through it, safely, into the cool night air.", "How did Rafael save the residents?", [["🚪", "He painted a door"], ["🚒", "He drove a fire engine"], ["💧", "He sprayed water"]]),
  A("as-y6-09", "Grandfather's Impossible Garden", "🌻", 1030, "Grandfather Okonkwo's tiny garden in Manchester grew impossible things: mangoes, pineapples and a banana tree that leaned over the fence. Scientists from the university came to study the soil, but they went away baffled. Then, one winter, Grandfather fell ill and went into hospital, and his plants began to wither. No heat lamps could save them. His granddaughter, Chidinma, remembered how he had talked and sung to them every morning. So she did the same, telling them stories and singing his favourite song. By spring, the garden was flourishing again. When Grandfather returned, he smiled. “You found the secret,” he said.", "What was the secret of the garden?", [["🗣️", "Talking and singing to the plants"], ["💡", "Heat lamps"], ["🧪", "Special fertiliser"]]),
  A("as-y6-10", "The Map That Drew Itself", "🗺️", 1040, "In her grandmother's dusty attic, Isla discovered a blank map that inked itself wherever she walked. Curious, she followed its wandering lines down the creaking stairs and through a secret door hidden in the garden hedge. Beyond lay a forgotten kingdom of talking foxes and floating lanterns, frozen beneath an ancient enchantment. An elderly fox limped towards her. “Only someone who finishes the map can wake us,” he whispered. So Isla walked through silent forests and over sleeping bridges until dawn. As the final line appeared on the parchment, the entire kingdom stretched, yawned and slowly came back to life.", "What happened to the map as Isla walked?", [["🖋️", "It drew itself"], ["🔥", "It burned"], ["🦊", "A fox stole it"]]),
];

const BY_LEVEL: Record<string, Passage[]> = {
  starter: STARTER,
  year1: YEAR1,
  year2: YEAR2,
  year3: YEAR3,
  year4: YEAR4,
  year5: YEAR5,
  year6: YEAR6,
};

/** The assignment stories for a reading level ([] if it has none). */
export function assignmentStories(levelId: string): Passage[] {
  return BY_LEVEL[levelId] ?? [];
}

/** One assignment story by id, wherever it's filed. */
export function findAssignmentStory(id: string): Passage | null {
  for (const list of Object.values(BY_LEVEL)) {
    const hit = list.find((p) => p.id === id);
    if (hit) return hit;
  }
  return null;
}

/** A child's assignment story and its level: one of these stories, or (for a
    story set before they existed) a Guided Reading passage. */
export function storyFor(storyId: string, levelId: string): { passage: Passage; level: PassageLevel } | null {
  const passage = findAssignmentStory(storyId);
  const level = passageLevels.find((l) => l.id === levelId);
  if (passage && level) return { passage, level };
  return findPassage(storyId, levelId);
}
