import { findPassage, passageLevels, type Passage, type PassageLevel } from "@/app/passages";
import type { StoryQuiz } from "@/app/stories";

/* The stories children get as their assignment: proper storybook tales,
   written to be enjoyed, in the spirit of the funny, warm, larger-than-life
   books children love: a narrator with a voice, characters with silly
   names, comic disasters, a twist, and a heart at the end. All original.

   Kept apart from the Guided Reading passages (timed read-alouds). Every
   story is short, 50 to 80 words, so it fits on one page; what grows
   through the levels is the sentence length and the vocabulary.

   The Lexile figures are estimates within each level's band. */

function A(
  id: string,
  title: string,
  emoji: string,
  lexile: number,
  text: string,
  question: string,
  options: [string, string][],
): Passage {
  const quiz: StoryQuiz = {
    question,
    options: options.map(([e, l]) => ({ emoji: e, label: l })),
    answer: 0,
  };
  return { id, title, emoji, lexile, text, quiz };
}

const STARTER: Passage[] = [
  A("as-st-01", "The Red Egg", "🥚", 50, "A hen has a big egg. It is not a hen egg. It is red and hot! Tap, tap, tap. Crack! Out pops a little dragon. The hen is in a fix. The dragon cannot cluck. It can puff! Puff, puff. Then the hen hugs the dragon. It is her pet now. Cluck, puff! Cluck, puff!", "What pops out of the egg?", [["🐉", "A dragon"], ["🐤", "A chick"], ["🐍", "A snake"]]),
  A("as-st-02", "Pig Wants a Bath", "🐷", 50, "Pig is in the mud. Pig is not pink. Pig is a big mud blob! Mum Pig is cross. “Get in the tub, Pig!” Pig gets in the tub. Scrub, scrub, rub. Pig is pink! Pig is so pink. Then Pig hops out. Pig runs and runs and runs... back to the mud. Splat! “PIG!” yells Mum.", "Where does Pig run at the end?", [["🟤", "Back to the mud"], ["🛁", "To the tub"], ["🛏️", "To bed"]]),
  A("as-st-03", "Ten Hens in a Van", "🚐", 50, "Ten hens get in a van. Ten hens in a van is a lot of hens! The van is red. The hens sit and sit. Then a fox sees the van. “Yum,” says the fox. The fox gets in the van. Ten hens peck the fox. Peck, peck, peck! The fox jumps out. Run, fox, run! The hens are the bosses of the van.", "Who pecked the fox?", [["🐔", "Ten hens"], ["🐶", "A dog"], ["🐱", "A cat"]]),
  A("as-st-04", "Ted Can Fly", "🧸", 50, "Ted is a big teddy. At night, Ted gets up. He has a red cape. Ted jumps on the bed. Up, up, up he goes! Ted can fly! He zips past the moon. He waves at a star. Then the sun pops up. Ted zips back to bed. Sam gets up and hugs Ted. Sam has no idea!", "What can Ted do at night?", [["🦸", "Fly"], ["🏊", "Swim"], ["🍳", "Cook"]]),
  A("as-st-05", "The Bug Who Was King", "👑", 50, "A little bug finds a gold ring. He puts it on his head. “I am the king of the pond!” he says. The fish nod. The frog bows. The duck quacks. Then the rain comes. Plop, plop! The ring fills up with rain. The king has a bath in his crown! “This is fit for a king,” he says.", "What did the bug put on his head?", [["💍", "A gold ring"], ["🎩", "A hat"], ["🍃", "A leaf"]]),
  A("as-st-06", "Kit and the Magic Mat", "🪄", 50, "Kit the cat has a red mat. But it is not just a mat. It is a magic mat! Kit sits on it. Up it gets! The mat zips up into the sky. Kit and the mat fly to the sun. “Too hot!” says Kit. They fly to the moon. “Too cold!” says Kit. They fly back to bed. “Just right,” says Kit.", "What can the magic mat do?", [["🪄", "Fly"], ["🎵", "Sing"], ["🍽️", "Cook"]]),
  A("as-st-07", "The Big Bone", "🦴", 50, "Rex the dog digs in the sand. Dig, dig, dig. He gets a bone. It is a big bone. He digs and digs. It is a big, big bone! Then the bone gets up. It is a dinosaur! “Hello,” says the dinosaur. “Can I have a bun?” Sam gets him a bun. Rex is not glad. He wants his bone back!", "What did Rex dig up?", [["🦖", "A dinosaur"], ["🪙", "A coin"], ["🐚", "A shell"]]),
  A("as-st-08", "The Duck Who Did Not Quack", "🦆", 50, "A duck sat on a log. Ducks quack. That is their job. But this duck did not quack. This duck went MOO! The ducks got a fright. A frog fell in. A cow ran up. “Is that my mum?” said the cow. The duck went red. “Sorry,” said the duck. “I had a cold.”", "What did the duck say?", [["🐮", "Moo"], ["🦆", "Quack"], ["🐶", "Woof"]]),
  A("as-st-09", "The Pot That Did Not Stop", "🍲", 50, "Gran has a magic pot. “Cook, pot, cook!” says Gran. Hot soup fills the pot. Yum! “Stop, pot, stop!” says Gran, and it stops. One day, Gran is out, and Sam is hungry. “Cook, pot, cook!” says Sam. Soup fills the pot. It fills the hut. It fills the street! Sam forgets the words. Then Gran gets back. “Stop, pot, stop!” Phew!", "What does the magic pot make?", [["🍲", "Soup"], ["🍪", "Biscuits"], ["🧃", "Juice"]]),
  A("as-st-10", "Big Bad Bob", "🐻", 50, "Bob is a big, bad bear. “I am big,” says Bob. “I am bad. I can ROAR!” Bob gets up on a rock. ROAR! Then a bird sits on Bob's nose. Tweet, tweet. Bob runs off! Bob hides in his den. Bob is big. Bob is bad. But Bob is not fond of birds.", "What made Bob run off?", [["🐦", "A bird"], ["🐍", "A snake"], ["🦁", "A lion"]]),
];

const YEAR1: Passage[] = [
  A("as-y1-01", "The Grumpiest Goat in the World", "🐐", 300, "Gertie was the grumpiest goat in the world. When the sun came out, she said, “Too hot!” When it rained, she said, “Too wet!” One day, a tiny lamb came to the farm. It bounced up to Gertie. Boing! Boing! Then it gave her a big, woolly hug. Gertie went pink. Then the corner of her mouth went up. The hens fell off their perch. Gertie was smiling!", "Who made Gertie smile?", [["🐑", "A tiny lamb"], ["🐔", "A hen"], ["👨‍🌾", "The farmer"]]),
  A("as-y1-02", "Sir Snorebert", "🛡️", 330, "Sir Snorebert was the bravest knight in the land. But he could never stay awake. One day, a dragon flew over the castle. “Wake up!” shouted the king. Sir Snorebert just snored. It was the loudest snore ever. It shook the towers. It blew off the king's crown! The dragon was so scared that it flew far away. The king gave Sir Snorebert a medal. He did not see it. He was asleep.", "How did Sir Snorebert scare the dragon away?", [["😴", "With a loud snore"], ["⚔️", "With his sword"], ["🐴", "On his horse"]]),
  A("as-y1-03", "The Mermaid's Magic Shell", "🧜", 360, "Mira the mermaid had a magic shell. When she sang into it, the waves danced. One day, a greedy crab stole it! Mira swam after him. “Give it back!” she called. The crab hid in a dark cave. So Mira sang a soft lullaby. The crab yawned. Then he fell fast asleep. Mira took her shell and swam home. That night, the waves danced until dawn.", "How did Mira get her shell back?", [["🎵", "She sang a lullaby"], ["🗡️", "She fought the crab"], ["🎁", "She gave the crab a present"]]),
  A("as-y1-04", "Mr Muddle's Magic Socks", "🧦", 380, "Mr Muddle bought some purple socks with yellow spots. “They are magic,” said the shopkeeper. Mr Muddle put them on. At once, his feet began to dance! They danced him out of the door. They danced him down the road. Tap, tap, twirl! People clapped. A dog joined in. By teatime, Mr Muddle was very tired. He locked the socks in a drawer. Even now, at night, he can hear them tapping.", "What did the magic socks make Mr Muddle do?", [["💃", "Dance"], ["🏃", "Run"], ["😴", "Sleep"]]),
  A("as-y1-05", "The Cat Who Thought She Was a Dog", "🐱", 400, "Mimi was a cat. She had whiskers and a long tail. But Mimi thought she was a dog! She fetched sticks. She chased the postman. She went for walks on a lead. People stared. Then a dog called Bruno moved in next door. Bruno curled up in the sun and purred. Bruno thought he was a cat! They swapped jobs at once, and everyone was much happier.", "What did Bruno think he was?", [["🐱", "A cat"], ["🐶", "A dog"], ["🐟", "A fish"]]),
  A("as-y1-06", "The Giant's Tiny Problem", "🦶", 420, "Gus was a giant. He was as tall as a tree. But Gus had a tiny problem. A mouse lived in his shoe! Every time Gus walked, the mouse squeaked. Squeak, squeak! The other giants laughed at him. So Gus made the mouse a little house. He put it in his pocket. Now the mouse rides with him everywhere. It has the best view in town!", "Where did the mouse live at first?", [["👟", "In Gus's shoe"], ["🏠", "In a house"], ["🎩", "In a hat"]]),
  A("as-y1-07", "The Tooth Fairy's Day Off", "🧚", 440, "Lily put her tooth under her pillow. But the Tooth Fairy had a cold, so she sent her little brother, Dennis. Dennis bumped into the lamp. He fell into the goldfish bowl. Splash! Then he forgot why he had come. He took the tooth and left a sock! In the morning, Lily wrote a note. “Dear Tooth Fairy, I think there has been a mix-up.” The next night, there were two coins.", "What did Dennis leave under the pillow?", [["🧦", "A sock"], ["🪙", "A coin"], ["🍪", "A biscuit"]]),
  A("as-y1-08", "Sang Kancil and the Crocodiles", "🐊", 460, "Sang Kancil was a small mouse deer, but he was very clever. He wanted the fruit across the river. But the river was full of crocodiles! “The King wants to count you,” said Kancil. “Please line up!” The crocodiles lined up across the river. Kancil hopped on their backs. “One, two, three...” Hop, hop, hop! He reached the other side. “Thank you for the bridge!” he laughed.", "How did Kancil cross the river?", [["🐊", "On the crocodiles' backs"], ["🛶", "In a boat"], ["🏊", "He swam"]]),
  A("as-y1-09", "The Wizard's Wobbly Wand", "🧙", 490, "Wizard Wilf had a wobbly wand. When he tried to make a cake, he made a snake! When he tried to make it rain, he made a train! Wilf was very upset. Then his cat, Pickle, looked closely at the wand. “You are holding it upside down,” she said. Wilf turned the wand round. Poof! A big chocolate cake appeared. Wilf and Pickle ate it all up.", "What did Wilf make when he tried to make a cake?", [["🐍", "A snake"], ["🚂", "A train"], ["🌧️", "Rain"]]),
  A("as-y1-10", "The Moon Wants a Holiday", "🌙", 520, "The Moon was tired. “I want a holiday,” she said. So she floated down to the beach. She put on sunglasses and had an ice cream. But the sky was very dark. Owls bumped into trees. Cats fell off walls. A girl called Nora went to the beach. “Please come back,” she said. “We miss you.” So the Moon went back. Now she has one holiday a month.", "Who asked the Moon to come back?", [["👧", "Nora"], ["🦉", "An owl"], ["🐱", "A cat"]]),
];

const YEAR2: Passage[] = [
  A("as-y2-01", "The Day the Teacher Turned Into a Frog", "🐸", 480, "Mr Bunting, the strictest teacher at school, never smiled. One morning, someone put green powder in his tea. Puff! He turned into a frog wearing tiny glasses. Class 2B cheered. They ate crisps and painted the ceiling. But soon the room felt too quiet. Priya gave the frog a little kiss to say sorry. Puff! Mr Bunting was back, with pond weed in his hair. And, for the first time ever, he laughed.", "What did Priya do to turn the frog back?", [["💋", "Gave it a kiss"], ["🍵", "Gave it tea"], ["📚", "Read it a book"]]),
  A("as-y2-02", "Nenek's Magic Wok", "🥘", 500, "Nenek had a magic wok. Whatever she cooked in it made people kind. One day, a grumpy giant stomped into the kampung, shouting and stamping. Everyone hid. But Nenek calmly cooked a plate of nasi lemak in her wok and offered it to him. The giant took one bite. His frown melted away. “Thank you,” he whispered. Now he helps Nenek carry her shopping every Saturday.", "What did the magic wok make people?", [["😊", "Kind"], ["😴", "Sleepy"], ["💪", "Strong"]]),
  A("as-y2-03", "Kevin the Talking Rock", "🪨", 510, "Ruby found a grey rock in the garden. To her surprise, it yawned. “Good morning,” said the rock. “My name is Kevin.” Kevin was a thousand years old, and he knew every story in the world. Every night, he told Ruby a new one. Her friends did not believe her. When they visited, Kevin stayed silent. But as soon as they left, he winked.", "What did Kevin tell Ruby every night?", [["📖", "A story"], ["🎵", "A song"], ["⭐", "A wish"]]),
  A("as-y2-04", "Captain Cutlass and the Very Small Ship", "🏴‍☠️", 530, "Captain Cutlass was a fierce pirate, but his ship was really a bathtub with a sail. Other sailors laughed at him. One stormy night, a big ship sank. Its sailors could not swim! Captain Cutlass rowed out and pulled all seventeen into his bath. He took them safely home. They gave him a huge new ship as a thank-you. He gave it back. “Too big,” he said.", "What was Captain Cutlass's ship really?", [["🛁", "A bathtub"], ["🚢", "A huge ship"], ["🛶", "A canoe"]]),
  A("as-y2-05", "The Girl Who Could Talk to Clouds", "☁️", 550, "Ella could talk to clouds. One summer, the farmers' fields were dry and dusty. “Please, clouds,” Ella called, “we need rain!” But the clouds were too busy racing each other across the sky. So Ella challenged them to a race. She ran up the hill as fast as she could. The clouds raced after her and bumped together. Crash! Rain poured down on the fields.", "How did Ella make the clouds bump together?", [["🏃", "She raced them"], ["🎶", "She sang to them"], ["🪁", "She flew a kite"]]),
  A("as-y2-06", "Uncle Bernard's Bouncing Bed", "🛏️", 560, "Uncle Bernard bought the bounciest bed ever made. That night, he jumped into it. BOING! He shot up through the roof in his pyjamas, holding his teddy. He bounced over the church and the school. “Lovely evening!” he called to Mrs Patel. At last, he landed back on his bed and fell asleep. In the morning, he said he had dreamed of flying. Nobody mentioned the hole in the roof.", "Where did Uncle Bernard land at the end?", [["🛏️", "Back on his bed"], ["🌊", "In the river"], ["⛪", "On the church"]]),
  A("as-y2-07", "The Shy Dragon", "🐉", 580, "Fizz the dragon was very shy. When she blushed, smoke puffed out of her ears, and the villagers ran away screaming. One winter, the village ran out of firewood. A boy called Tomas climbed up to her cave. “Please help,” he said. “We're freezing.” Fizz gently breathed warm air over the village. The snow melted. The houses grew warm. Everyone cheered. Fizz blushed, but this time she didn't mind.", "What happened when Fizz blushed?", [["💨", "Smoke came out of her ears"], ["🔥", "She breathed fire"], ["🌈", "She turned rainbow"]]),
  A("as-y2-08", "Mr Plum's Unusual Shop", "🏪", 590, "Mr Plum's strange shop sold things you didn't know you needed. He gave Leo a little brass key. “What does it open?” asked Leo. Mr Plum just smiled. The key did not open the front door. It did not open the biscuit tin. Then Leo's sister got locked in the bathroom! Leo tried the key. Click! The door opened. When Leo went back to say thank you, the shop had vanished.", "What did the brass key open?", [["🚪", "The bathroom door"], ["🍪", "The biscuit tin"], ["🚲", "His bike lock"]]),
  A("as-y2-09", "The Great Hamster Escape", "🐹", 600, "Every night, Nibbles the hamster practised his escape. On Friday, he picked the lock with a sunflower seed. He slid down the table leg and dived into the teacher's handbag. Inside, he ate mints and half a sandwich, then fell asleep. On Monday, Miss Hart reached for a pen and screamed! Out rolled Nibbles, with a mint on his ear. Now he is planning his next escape.", "Where did Nibbles hide?", [["👜", "In the teacher's handbag"], ["📚", "Behind the books"], ["🎒", "In a school bag"]]),
  A("as-y2-10", "Granny Goes to Space", "🚀", 610, "Granny Joan was ninety-two, and everyone said she was too old for space. So she built a rocket from a dustbin and a giant firework. She wore a goldfish bowl as a helmet. WHOOSH! She zoomed past the clouds and looped around the Moon. She even had tea with an astronaut. Then she landed in the vegetable patch. “Too old?” she said. “Next week, I'm going to Mars.”", "What did Granny use as a helmet?", [["🐠", "A goldfish bowl"], ["🪣", "A bucket"], ["🎩", "A top hat"]]),
];

const YEAR3: Passage[] = [
  A("as-y3-01", "The Boy Who Swallowed a Thunderstorm", "⛈️", 680, "One rainy afternoon, Felix Fennimore accidentally swallowed a small thundercloud. Whenever he got cross, he rumbled, and when he ate sprouts, rain drizzled from his ears. Then a terrible drought came, and the village well dried up. Felix stood in the dusty fields, thought about every annoying thing that had ever happened to him, and roared. Out burst the storm! Rain poured down, and the farmers danced in the mud.", "How did Felix make the rain come?", [["😠", "He got very cross and roared"], ["💃", "He did a rain dance"], ["💧", "He used a hose"]]),
  A("as-y3-02", "Detective Dumpling and the Missing Mangoes", "🥭", 690, "Detective Dumpling, aged eight, was the only detective in Kampung Bunga. When Pak Ali's twelve mangoes vanished, she took the case. Mrs Lim's goat had an alibi, and the postman was allergic to mangoes. Then she spotted a trail of mango peel that led from the bus stop all the way to the jungle. Up in a tree sat a very fat, very happy monkey. It burped. The case was solved, and her fee was one ripe mango.", "Who stole the mangoes?", [["🐒", "A monkey"], ["🐐", "Mrs Lim's goat"], ["📮", "The postman"]]),
  A("as-y3-03", "The Boy Who Shrank", "🔍", 700, "When Barnaby sneezed during science, he suddenly shrank to the size of a pea. Nobody noticed. He climbed onto the teacher's desk, dodged a gigantic pencil and rode a ladybird across the classroom. Then he spotted the class goldfish trapped behind a fallen book. Using all his tiny strength, he pushed the book aside. The grateful goldfish blew a magic bubble, and Barnaby popped back to his normal size.", "Who helped Barnaby return to his normal size?", [["🐟", "The goldfish"], ["🐞", "A ladybird"], ["👩‍🏫", "The teacher"]]),
  A("as-y3-04", "The Unicorn Who Hated Rainbows", "🦄", 710, "Every unicorn in Glimmerdale adored rainbows, except Clementine. She found them far too bright, and she preferred grey clouds and muddy puddles. The other unicorns thought she was very strange. Then, one day, a terrible storm swallowed every rainbow in the sky. The unicorns panicked, but Clementine galloped happily into the gloom. Splashing through puddles, she found the lost rainbows hiding underneath a cloud and led them safely home.", "Where were the lost rainbows hiding?", [["☁️", "Underneath a cloud"], ["🌊", "In the sea"], ["🏔️", "On a mountain"]]),
  A("as-y3-05", "The Library at the Bottom of the Sea", "🐙", 720, "While snorkelling, Marina spotted a light deep beneath the bay. She dived down and found a stone door marked: THE SUNKEN LIBRARY. NO SPLASHING. The librarian was an elderly octopus wearing four pairs of spectacles. Marina read all afternoon, from pirate diaries to a cross lobster's cookbook. She borrowed one silver book. It is still on her shelf, and if you open it, you can hear the sea.", "Who was the librarian?", [["🐙", "An octopus"], ["🦀", "A crab"], ["🐋", "A whale"]]),
  A("as-y3-06", "Mrs Mangle's Magnificent Moustache", "👵", 730, "Nobody knew why Mrs Mangle, the baker, grew a moustache. By Friday, it was long enough to tuck into her apron. At the Great Bake-Off, she carried out an enormous, wobbly cake. Suddenly, the top layer began to slide! Quick as a flash, she flicked her moustache underneath and held it perfectly in place. She won first prize. “You never know when you'll need one,” she said.", "How did Mrs Mangle save her cake?", [["👨", "With her moustache"], ["🥄", "With a big spoon"], ["🧤", "With oven gloves"]]),
  A("as-y3-07", "The Robot Who Wanted to Be a Chicken", "🤖", 740, "Unit X-9000 was the cleverest robot ever built. It could speak forty languages and build bridges. But it did not want to. It wanted to be a chicken. So Professor Gearbox took it to a farm. It learned to strut and peck, and it made feathers from tin foil. It never laid an egg. But it designed the world's best henhouse, with a disco ball. The hens were delighted.", "What did the robot design for the hens?", [["🏠", "The best henhouse in the world"], ["🌉", "A bridge"], ["🚀", "A rocket"]]),
  A("as-y3-08", "The Night the Toys Went on Strike", "🧸", 760, "Maisie was not kind to her toys. She left her teddy, Captain Buttons, out in the rain and drew a moustache on her doll. So one night, the toys went on strike. In the morning, Maisie found them in the garden shed, holding signs that said: WE WANT RESPECT. Maisie felt ashamed. She said sorry to every toy and carried them home. That night, Captain Buttons winked.", "Where did Maisie find her toys?", [["🛖", "In the garden shed"], ["🛏️", "Under the bed"], ["📦", "In the attic"]]),
  A("as-y3-09", "Granny's Great Gorilla Mix-Up", "🦍", 780, "Granny Pearl ordered a fluffy brown rug online, but she clicked the wrong button. A fluffy brown gorilla called Gordon arrived instead. Granny was short-sighted, so she stood on him to reach the top shelf. Gordon was too polite to complain. When her grandson saw the rug yawn, he screamed. But Granny refused to let Gordon go. “He does the gardening,” she said, “and he's an excellent listener.”", "What did Granny Pearl think Gordon was?", [["🟫", "A rug"], ["🧸", "A teddy"], ["🐻", "A bear"]]),
  A("as-y3-10", "The Kite That Flew Away With Mr Tan", "🪁", 800, "For fifty years, Mr Tan had flown kites every Sunday. This year, he built one as big as a bus. “Too big,” warned his wife. He let it go, and the wind lifted him right off the sand! He floated over a fishing boat, and some monkeys threw a banana at him. An hour later, he landed beside his wife's deckchair. “Too big?” she asked. “Perhaps,” he admitted.", "What did the monkeys throw at Mr Tan?", [["🍌", "A banana"], ["🥥", "A coconut"], ["🪨", "A stone"]]),
];

const YEAR4: Passage[] = [
  A("as-y4-01", "The Headmaster Who Was Secretly a Wizard", "🧙", 790, "Dr Hushworth, the strict headmaster, hated noise. Then, during a silent assembly, Amira noticed something peculiar: a tiny wand poking out of his sleeve. That afternoon, she followed him to his office and watched through the keyhole as he turned a pile of homework into a flock of paper birds. Suddenly, he spun round and saw her. “Can you keep a secret?” he asked. Now, every Friday, he teaches Amira magic.", "What did the headmaster turn the homework into?", [["🐦", "Paper birds"], ["🐸", "Frogs"], ["🍰", "A cake"]]),
  A("as-y4-02", "The Secret Diary of a Very Nervous Lighthouse", "🗼", 800, "Monday: I am Lumi, a lighthouse who is afraid of the dark. Embarrassing, I know. Tuesday: During the storm, I pretended to be a very tall tree. Thursday: Through the fog, I saw a little boat heading for the rocks. I was trembling, but I thought: how frightened must that girl be? So I shone brighter than ever. She was saved. Friday: Being brave means shining anyway.", "What was Lumi the lighthouse scared of?", [["🌑", "The dark"], ["🌊", "Big waves"], ["🐦", "Seagulls"]]),
  A("as-y4-03", "The Grandad Who Lived in a Teapot", "🫖", 810, "Oliver's grandad was only five centimetres tall, and he lived inside a teapot on the kitchen shelf. Nobody else knew. Each evening, Oliver lifted the lid, and Grandad told him stories about sailing teacup boats across the sink. One morning, Mum decided to make a pot of tea. Oliver dived across the kitchen and caught the teapot just in time. Since then, the family has drunk coffee, and Grandad is extremely grateful.", "Where did Grandad live?", [["🫖", "In a teapot"], ["☕", "In a teacup"], ["🏠", "In a dolls' house"]]),
  A("as-y4-04", "The Ghost Who Was Afraid of Children", "👻", 820, "For three hundred years, Lady Wimbledon's ghost had terrified everyone at Grimthorpe Castle. Then a family with five fearless children moved in. When she rattled her chains, they made a swing out of them. When she floated past carrying her own head, little Hattie asked to hold it. Eventually, Hattie handed her a book. “Read us a story,” she said. Now Lady Wimbledon reads bedtime stories every night.", "What did the children ask Lady Wimbledon to do?", [["📖", "Read them a story"], ["⛓️", "Rattle her chains"], ["🏰", "Leave the castle"]]),
  A("as-y4-05", "The Inventor of Useless Things", "💡", 830, "Professor Ida Bloom invented useless things, such as umbrellas for ducks and a sock matcher that ate socks. Everybody laughed at her. Then a great flood swept through the town, and the water pumps broke. The desperate mayor paddled to her window for help. She switched her sock matcher to WATER, and it slurped up the whole flood overnight. The newspapers renamed her “the Inventor of Things We Didn't Know We Needed”.", "What did the Sock Matcher do in the flood?", [["💧", "It sucked up the water"], ["🧦", "It ate socks"], ["🍲", "It made soup"]]),
  A("as-y4-06", "The Night Market Mystery", "🏮", 840, "Every Wednesday at nine o'clock, the lights at the pasar malam went out, and food vanished: pisang goreng, chicken wings, even a pot of laksa. People blamed a ghost. Siti hid under a stall with a torch. When the lights failed, she spotted a monitor lizard carrying away a tray of banana fritters. She followed it to a drain, where six hungry babies were waiting. The thief was simply a mother doing her shopping.", "Who was stealing the food?", [["🦎", "A mother monitor lizard"], ["👻", "A ghost"], ["👦", "Teenagers"]]),
  A("as-y4-07", "The Boy Who Could Talk to Pigeons", "🐦", 850, "After swallowing a feather, Sam could understand pigeons. Unfortunately, pigeons never stopped arguing about crumbs. Then the mayor's dog went missing, and the whole city searched for days. Sam overheard two pigeons gossiping: the dog was stuck in a drainpipe by the river. Sam rescued him. As a reward, he asked only for a bag of bread for the pigeons. Now they bow when he passes.", "Where was the missing dog?", [["🌉", "In a drainpipe by the river"], ["🏞️", "In the park"], ["🏠", "On a roof"]]),
  A("as-y4-08", "The Supermarket at Midnight", "🛒", 860, "At midnight, when the doors were locked, the food in Bumbleton's Supermarket came alive. The bananas held races down aisle three, and the tins of soup sang in harmony. One night, a mischievous mouse sneaked inside and began nibbling the cheese. Immediately, the vegetables formed an army. The carrots charged, and the potatoes rolled in to trap him. By morning, the mouse had been escorted outside, and everything was neatly back on the shelves.", "Who chased the mouse?", [["🥕", "The vegetables"], ["🍌", "The bananas"], ["🥫", "The tins of soup"]]),
  A("as-y4-09", "The Elephant Who Forgot", "🐘", 860, "Mabel was an elephant who forgot everything, even where her trunk was. The herd sighed. Then a drought came, and old Grandmother Tembo couldn't remember the way to the secret spring. But because Mabel never remembered anything, she looked carefully at everything. She had noticed birds flying north and returning with wet feathers. “Follow the birds!” she trumpeted. They found the spring. Forgetting, it seemed, had taught her to notice.", "What helped Mabel find the spring?", [["🐦", "She followed the birds"], ["🗺️", "She used a map"], ["🧠", "She remembered the way"]]),
  A("as-y4-10", "The Toaster That Granted Wishes", "🍞", 870, "When Leo's family bought a second-hand toaster, they had no idea it was enchanted. Every slice of toast it produced granted one wish. Leo wished for a puppy, and one appeared, licking butter from his fingers. His sister wished for snow, and the kitchen filled with snowflakes. Then Dad, still half asleep, wished for some peace and quiet. The toaster sighed, popped out a final slice and never spoke again.", "What appeared when Leo made his wish?", [["🐶", "A puppy"], ["❄️", "Snow"], ["🍰", "A cake"]]),
];

const YEAR5: Passage[] = [
  A("as-y5-01", "The Boy Who Was Allergic to Adventure", "🗺️", 900, "Horace Plimpton was genuinely allergic to adventure: anything exciting gave him purple spots. Then his great-aunt left him a map and a note: “The cure is at the X.” Horace set off, sneezing; he was chased by geese and got lost in a maze. At the X, on a hilltop, he found only a bench carved with the words: “The cure is to keep going.” His spots faded completely.", "What was the cure for Horace's allergy?", [["🚶", "To keep going"], ["💊", "A special medicine"], ["💰", "Finding treasure"]]),
  A("as-y5-02", "The Substitute Teacher From the Year 3000", "🛸", 910, "The substitute teacher, Ms Zyx, wore silver boots, ate her yoghurt pot and all, and seemed astonished by pencils. Kofi confronted her: “You're from the future.” She admitted it. She was a historian from the year 3000, studying a real classroom. “In my time, machines entertain everyone constantly,” she explained, “so nobody is ever bored, and nobody imagines anything new.” She left a note: “Thank you for the boredom.”", "Why did Ms Zyx visit the past?", [["📚", "To study a real classroom"], ["🍦", "To eat yoghurt"], ["🔭", "To see the Sun"]]),
  A("as-y5-03", "The Durian Tree That Wouldn't Share", "🌳", 920, "Encik Kamal owned the finest durian tree in Malaysia, but he fenced it in and refused to share a single fruit. One year, the tree stopped fruiting altogether. “Perhaps it's lonely,” suggested little Nurul. That night, sitting alone beneath its empty branches, Encik Kamal understood. He tore down the fences and put up a sign: EVERYONE WELCOME. Within a week, the branches were heavy with durians.", "What made the durian tree fruit again?", [["🤝", "Sharing it with everyone"], ["🧪", "Expensive powder"], ["📜", "A lawyer's letter"]]),
  A("as-y5-04", "The Spelling Bee That Buzzed", "🐝", 930, "Agatha Grimwhistle was the best speller at Thistlebottom Primary, which was why the real Spelling Bee chose her. It was a tiny golden bee that could buzz any word into existence. “Spell carefully,” it warned. Agatha spelled “butterfly”, and a cloud of butterflies burst from her pencil. Then her classmate snatched the pencil and spelled “dinosaur” wrongly. A very confused creature appeared, wearing a tutu. Agatha corrected the spelling immediately.", "What happened when Agatha spelled “butterfly”?", [["🦋", "Butterflies appeared"], ["🐝", "The bee flew away"], ["✏️", "Her pencil broke"]]),
  A("as-y5-05", "The Last Dragon in Kuala Lumpur", "🐉", 940, "On a skyscraper in Kuala Lumpur lived a secret dragon, Seri Naga, known only to Mei Ling. “Where are the other dragons?” Mei Ling asked. “When the forests shrink,” said Seri Naga sadly, “dragons fall asleep.” So Mei Ling started a club where every member planted a tree. When the half-millionth tree was planted, deep in the rainforest, an ancient dragon opened one golden eye. The dragons were waking up.", "What did members of the Dragon Keepers have to do?", [["🌱", "Plant a tree"], ["🐉", "Find a dragon"], ["🍵", "Make teh tarik"]]),
  A("as-y5-06", "The Sweet Shop Owner Who Hated Children", "🍬", 950, "Mr Grimsby owned a wonderful sweet shop, yet he despised children. His parrot even screeched “Hurry up!” at customers. One evening, a girl with holes in her shoes placed a single coin on the counter. “It's my poorly brother's birthday,” she said. Something in Mr Grimsby's chest creaked. He filled a bag with sweets and pushed the coin back. The next day, his sign read: FREE SAMPLES ON FRIDAYS.", "What did Mr Grimsby give the girl?", [["🍭", "A bag full of sweets, and her coin back"], ["🧥", "A new coat"], ["🦜", "His parrot"]]),
  A("as-y5-07", "The World's Worst Superhero", "🦸", 960, "On his eleventh birthday, Archie got superpowers, but they were hopeless: he could fly only two centimetres high and see through nothing but sandwiches. Then thieves stole a priceless diamond from the museum, and the police couldn't find it anywhere. Archie squinted at the leader's lunchbox. “It's in the sandwich!” he shouted. He hovered just high enough to trip the fleeing thief. Newspapers called him SANDWICH BOY.", "Where was the diamond hidden?", [["🥪", "In a sandwich"], ["🧥", "In a coat pocket"], ["🎒", "In a school bag"]]),
  A("as-y5-08", "The Girl Who Collected Lost Dreams", "🌙", 970, "Every night, Wren crept across the rooftops with a silver net, collecting the dreams that people forgot by morning. She stored them in glass jars on her windowsill, where they glowed like fireflies. One jar held an old man's dream of flying, abandoned seventy years earlier. Wren climbed through his window and gently returned it while he slept. The next morning, his neighbours were astonished to see him floating above his garden, laughing.", "What did Wren collect?", [["🌙", "Forgotten dreams"], ["✨", "Fireflies"], ["🧤", "Lost gloves"]]),
  A("as-y5-09", "The Cat Who Ran the Country", "🐈", 980, "Nobody knew how Tiddles, a fat ginger cat, became Prime Minister. His first law made afternoon naps compulsory. His second reserved all cardboard boxes for sitting in. His third banned the hoover. Surprisingly, people grew calmer, children built cardboard rockets, and families spent weekends together. The country became the happiest it had been for a century. Tiddles served one term, then fell asleep in a sunbeam.", "What did Tiddles' first law make compulsory?", [["😴", "Afternoon naps"], ["📦", "Sitting in boxes"], ["🧹", "Hoovering"]]),
  A("as-y5-10", "The Piano That Played at Midnight", "🎹", 990, "Every night at midnight, the old piano in the abandoned theatre began playing by itself. The townspeople were convinced that it was haunted. Ottilie, who was braver than most, crept inside to investigate. Instead of a ghost, she discovered a family of mice dancing across the keys, performing for an audience of moths. Ottilie sat down beside them and played a duet. Now the theatre has reopened, and the mice perform every Saturday.", "Who was playing the piano?", [["🐭", "A family of mice"], ["👻", "A ghost"], ["🦉", "An owl"]]),
];

const YEAR6: Passage[] = [
  A("as-y6-01", "The Boy Who Sold His Shadow", "🌑", 960, "Jasper sold his shadow to a stranger for a hundred pounds and bought a bicycle. Soon, however, he began forgetting things: his grandmother's laugh, the smell of the sea. Desperate, he found the stranger's shop, lined with rolled-up shadows. Instead of paying, Jasper walked into the sunlight, deliberately remembering every precious detail. With each memory, his shadow darkened again. The stranger, it turned out, could keep only what people surrendered.", "How did Jasper get his shadow back?", [["🧠", "By holding on to his memories"], ["💰", "By paying the stranger"], ["✂️", "By cutting it out"]]),
  A("as-y6-02", "The Bookshop That Moved", "📚", 970, "Mr Rahman's bookshop on Jalan Merdeka was enchanted: every night, it quietly moved to wherever a reader needed it most. One morning, developers arrived with bulldozers, determined to demolish it for a car park, but they found only an empty plot. Meanwhile, the shop had settled beside a hospital, where a lonely boy was waiting for an operation. Through its window, he glimpsed an extraordinary book about tigers. The shop had chosen its next customer.", "Where did the bookshop move to?", [["🏥", "Beside a hospital"], ["🏫", "Beside a school"], ["🏖️", "To the beach"]]),
  A("as-y6-03", "The Unusual Inheritance of Florence Fairbottom", "🏰", 980, "Florence inherited a crumbling Scottish castle and a curse: keep the castle's promise, or it would fall into the sea. Nobody remembered the promise. Exploring, she discovered the first Lady's diary hidden behind a portrait. Centuries earlier, the castle had promised to keep a light burning for anyone lost at sea. That night, Florence climbed the highest tower and lit a lantern. The cracks in the walls stopped spreading.", "What was the castle's promise?", [["🕯️", "To keep a light burning for anyone lost at sea"], ["💰", "To guard a treasure"], ["🦇", "To protect the bats"]]),
  A("as-y6-04", "The Day Everyone Told the Truth", "🤥", 990, "One March morning, something in the water made everyone in Little Fibbington incapable of lying. Chaos erupted: Mr Henderson admitted that his wife's porridge tasted like wallpaper paste. Yet by afternoon, people began confessing kinder truths. A grumpy postman told an old lady that her waving brightened his day, and two estranged brothers admitted they had forgotten their argument. Now the town celebrates Truth Day, when everyone says one true, kind thing.", "What good thing happened after the chaos?", [["💬", "People said kind, true things"], ["🏊", "The pool opened"], ["🥣", "The porridge got better"]]),
  A("as-y6-05", "The Lighthouse at the Edge of Time", "⏳", 1000, "Old Mrs Penhallow kept a lighthouse that shone not across the sea, but across the centuries. Ships from every age followed its beam: Viking longboats, Spanish galleons and, once, a bewildered submarine from the distant future. Each sailor signed her logbook in gratitude. When Mrs Penhallow grew too frail to climb the stairs, she entrusted the lamp to her granddaughter, Morwenna. Inside the logbook, Morwenna discovered her own name, written there centuries earlier.", "What did the lighthouse shine across?", [["⏳", "The centuries"], ["🌊", "Only the sea"], ["🏙️", "The city"]]),
  A("as-y6-06", "The Kingdom of Lost Socks", "🧦", 1000, "Imogen fell through her broken washing machine into a cavern where millions of escaped socks had built a kingdom. Their king, an ancient Christmas sock, declared that they were free from smelly trainers forever. But Imogen noticed that many socks looked homesick. So she negotiated a treaty: gentle washing, sunshine drying, and partners of their choice. Since then, missing socks have decreased dramatically, though some still take holidays.", "What did Imogen agree with the King of the socks?", [["📜", "A treaty"], ["🧺", "A new washing machine"], ["🎉", "A party"]]),
  A("as-y6-07", "The Clockmaker's Apprentice", "⏰", 1010, "In the back room of his shop, Master Horologe kept a clock that hadn't ticked for a century. When the old clockmaker fell ill, his apprentice, Pip, finally lifted its dust sheet. Its brass plate read: THE HEART OF TICKLETHWAITE. Working all night, she repaired it. As it began ticking, the town transformed: rivers sparkled, gardens bloomed, and upstairs, her master's cough vanished completely.", "What happened when the great clock ticked again?", [["🌸", "The town came back to life"], ["🌧️", "It began to rain"], ["🔔", "All the bells rang"]]),
  A("as-y6-08", "The Boy Who Painted Doors", "🚪", 1020, "Whatever door Rafael painted on a wall became real. At first, he used his gift for mischief, painting escape routes from maths lessons and shortcuts to the biscuit cupboard. However, when a fire trapped the residents of an old apartment block, Rafael ran towards the flames. With trembling hands, he painted an enormous door on the outside wall. One by one, the residents stepped through it, safely, into the cool night air.", "How did Rafael save the residents?", [["🚪", "He painted a door"], ["🚒", "He drove a fire engine"], ["💧", "He sprayed water"]]),
  A("as-y6-09", "Grandfather's Impossible Garden", "🌻", 1030, "Grandfather's tiny Manchester garden grew impossible mangoes and pineapples, baffling university scientists. When he fell ill, the plants began dying, and no heat lamps could save them. His granddaughter Chidinma remembered how he talked and sang to them every morning. So she did the same, telling them stories and singing his song. By spring, everything flourished. When Grandfather returned, he smiled. “You found the secret,” he said.", "What was the secret of the garden?", [["🗣️", "Talking and singing to the plants"], ["💡", "Heat lamps"], ["🧪", "Special fertiliser"]]),
  A("as-y6-10", "The Map That Drew Itself", "🗺️", 1040, "In her grandmother's dusty attic, Isla discovered a blank map that inked itself wherever she walked. Curious, she followed its wandering lines through a secret door hidden in the hedge. Beyond lay a forgotten kingdom of talking foxes and floating lanterns, frozen beneath an ancient enchantment. “Only someone who finishes the map can wake us,” whispered an elderly fox. Isla walked until dawn. As the final line appeared, the entire kingdom yawned awake.", "What happened to the map as Isla walked?", [["🖋️", "It drew itself"], ["🔥", "It burned"], ["🦊", "A fox stole it"]]),
];

const BY_LEVEL: Record<string, Passage[]> = {
  starter: STARTER,
  year1: YEAR1,
  year2: YEAR2,
  year3: YEAR3,
  year4: YEAR4,
  year5: YEAR5,
  year6: YEAR6,
};

/** The assignment stories for a reading level ([] if it has none). */
export function assignmentStories(levelId: string): Passage[] {
  return BY_LEVEL[levelId] ?? [];
}

/** One assignment story by id, wherever it's filed. */
export function findAssignmentStory(id: string): Passage | null {
  for (const list of Object.values(BY_LEVEL)) {
    const hit = list.find((p) => p.id === id);
    if (hit) return hit;
  }
  return null;
}

/** A child's assignment story and its level: one of these stories, or (for a
    story set before they existed) a Guided Reading passage. */
export function storyFor(storyId: string, levelId: string): { passage: Passage; level: PassageLevel } | null {
  const passage = findAssignmentStory(storyId);
  const level = passageLevels.find((l) => l.id === levelId);
  if (passage && level) return { passage, level };
  return findPassage(storyId, levelId);
}
