import { findPassage, passageLevels, type Passage, type PassageLevel } from "@/app/passages";
import type { StoryQuiz } from "@/app/stories";

/* The stories children get as their assignment: proper storybook tales,
   written to be enjoyed, in the spirit of the funny, warm, larger-than-life
   books children love: a narrator with a voice, characters with silly
   names, comic disasters, a twist, and a heart at the end. All original.

   Kept apart from the Guided Reading passages (timed read-alouds). Every
   story is short, 50 to 80 words, so it fills a five-page book; what grows
   through the levels is the sentence length and the vocabulary.

   The Lexile figures are estimates within each level's band. */

function A(
  id: string,
  title: string,
  emoji: string,
  lexile: number,
  text: string,
  question: string,
  options: [string, string][],
): Passage {
  const quiz: StoryQuiz = {
    question,
    options: options.map(([e, l]) => ({ emoji: e, label: l })),
    answer: 0,
  };
  return { id, title, emoji, lexile, text, quiz };
}

const STARTER: Passage[] = [
  A("as-st-01", "The Big Fat Hat", "🎩", 50, "Dad has a hat. It is a big, fat, red hat. Dad sat on the hat. Squash! The hat is flat. Dad is sad. Mum got the hat. Mum hit it. Pop! Up it got. It is big and fat. But a cat is in it! The cat had a nap in Dad's hat. Dad is not sad now. But the cat is not glad. “Get out, cat!”", "What was in Dad's hat?", [["🐱", "A cat"], ["🐟", "A fish"], ["🍎", "An apple"]]),
  A("as-st-02", "Pig Wants a Bath", "🐷", 50, "Pig is in the mud. Pig is not pink. Pig is a big mud blob! Mum Pig is cross. “Get in the tub, Pig!” Pig gets in the tub. Scrub, scrub, rub. Pig is pink! Pig is so pink. Then Pig hops out. Pig runs and runs and runs... back to the mud. Splat! “PIG!” yells Mum.", "Where does Pig run at the end?", [["🟤", "Back to the mud"], ["🛁", "To the tub"], ["🛏️", "To bed"]]),
  A("as-st-03", "Ten Hens in a Van", "🚐", 50, "Ten hens get in a van. Ten hens in a van is a lot of hens! The van is red. The hens sit and sit. Then a fox sees the van. “Yum,” said the fox. The fox gets in the van. Ten hens peck the fox. Peck, peck, peck! The fox jumps out. Run, fox, run! The hens are the boss of the van.", "Who pecked the fox?", [["🐔", "Ten hens"], ["🐶", "A dog"], ["🐱", "A cat"]]),
  A("as-st-04", "Gran Can Kick", "⚽", 50, "Gran is not big. Gran is not fast. Ben has a ball. “Can I kick it?” said Gran. Ben is not sure. Gran runs. Gran kicks. BAM! The ball zips up and up and up. It is a big, big kick! It hits a bus. The bus stops. Ben gasps. Gran is the best. Ben has a lot to learn.", "What did the ball hit?", [["🚌", "A bus"], ["☀️", "The sun"], ["🏠", "A house"]]),
  A("as-st-05", "The Bug in My Bed", "🐛", 50, "I get in bed. I hug my ted. But I am not on my own. A bug is in my bed! The bug has six legs. It sits on my leg. Tickle, tickle! I am not sad. I am not mad. I am giggling! The bug is fun. But Mum is not fun. “Bug! Out!” said Mum. Bye, bug.", "How many legs does the bug have?", [["6️⃣", "Six"], ["2️⃣", "Two"], ["🔟", "Ten"]]),
  A("as-st-06", "Kit and the Jam", "🍓", 50, "Kit the cat likes jam. Kit gets on the box. Kit gets on the tin. Kit gets up to the jam pot. Lick, lick, lick. Yum! Kit is a jam cat. Kit has jam on his lip. Kit has jam on his leg. Kit has jam on his tum. Mum sees Kit. Mum is not happy. Now Kit is in the bath. Not yum!", "What did Kit lick?", [["🍓", "Jam"], ["🥛", "Milk"], ["🐟", "Fish"]]),
  A("as-st-07", "Dad and the Big Dig", "⛏️", 50, "Dad digs a pit. Dig, dig, dig. The pit gets big. The pit gets bigger. Dad is in the pit. “Help!” said Dad. “I am stuck in the pit!” Sam gets a rope. Mum gets a rope. The dog gets a bun. Tug, tug, tug! Up pops Dad. Dad is a mud man! The dog eats the bun.", "Who got stuck in the pit?", [["👨", "Dad"], ["🐶", "The dog"], ["👩", "Mum"]]),
  A("as-st-08", "The Duck Who Did Not Quack", "🦆", 50, "A duck sat on a log. Ducks quack. That is the job. But this duck did not quack. This duck went MOO! The ducks got a fright. A frog fell in. A cow ran up. “Is that my mum?” said the cow. The duck went red. “Sorry,” said the duck. “I had a cold.”", "What did the duck say?", [["🐮", "Moo"], ["🦆", "Quack"], ["🐶", "Woof"]]),
  A("as-st-09", "The Hot Pot", "🍲", 50, "Mum has a big pot. In the pot is a lot of hot soup. Dad wants the soup. Sam wants the soup. The dog wants the soup. But the pot is too hot. So they wait. And wait. And wait. Then the pot is not hot. But the pot is... empty! Gran had it all. Gran has a big tum.", "Who had all the soup?", [["👵", "Gran"], ["🐶", "The dog"], ["👦", "Sam"]]),
  A("as-st-10", "Big Bad Bob", "🐻", 50, "Bob is a big bad bear. “I am big,” said Bob. “I am bad. I can ROAR!” Bob gets up on a rock. ROAR! Then a bird sits on Bob's nose. Tweet, tweet. Bob runs off! Bob hid in his den. Bob is big. Bob is bad. But Bob is not fond of birds.", "What made Bob run off?", [["🐦", "A bird"], ["🐍", "A snake"], ["🦁", "A lion"]]),
];

const YEAR1: Passage[] = [
  A("as-y1-01", "The Grumpiest Goat in the World", "🐐", 300, "Gertie was the grumpiest goat in the world. When the sun came out, she said, “Too hot!” When it rained, she said, “Too wet!” One day, a tiny lamb came to the farm. It bounced up to Gertie. Boing! Boing! Then it gave her a big, woolly hug. Gertie went pink. Then the corner of her mouth went up. The hens fell off their perch. Gertie was smiling!", "Who made Gertie smile?", [["🐑", "A tiny lamb"], ["🐔", "A hen"], ["👨‍🌾", "The farmer"]]),
  A("as-y1-02", "Sir Snorebert", "🛡️", 330, "Sir Snorebert was the bravest knight in the land. But he could never stay awake. One day, a dragon flew over the castle. “Wake up!” shouted the king. Sir Snorebert just snored. It was the loudest snore ever. It shook the towers. It blew off the king's crown! The dragon was so scared that it flew far away. The king gave Sir Snorebert a medal. He did not see it. He was asleep.", "How did Sir Snorebert scare the dragon away?", [["😴", "With a loud snore"], ["⚔️", "With his sword"], ["🐴", "On his horse"]]),
  A("as-y1-03", "The Smelly Surprise", "🍈", 360, "Auntie Zaza brought home a big, spiky durian. “Smell that!” she said. Adam sniffed. His eyes watered. His socks curled. “It smells like a dinosaur's sock!” he gasped. The smell rolled down the street. The neighbours shut their windows. The cat moved house! Then Auntie gave Adam a tiny piece. It was sweet and creamy. “Can I have more?” asked Adam. The cat is still not speaking to him.", "What did Adam think the durian smelled like?", [["🧦", "A dinosaur's sock"], ["🌹", "A rose"], ["🍞", "Fresh bread"]]),
  A("as-y1-04", "Mr Muddle's Magic Socks", "🧦", 380, "Mr Muddle bought some purple socks with yellow spots. “They are magic,” said the shopkeeper. Mr Muddle put them on. At once, his feet began to dance! They danced him out of the door. They danced him down the road. Tap, tap, twirl! People clapped. A dog joined in. By teatime, Mr Muddle was very tired. He locked the socks in a drawer. But at night, he can still hear them tapping.", "What did the magic socks make Mr Muddle do?", [["💃", "Dance"], ["🏃", "Run"], ["😴", "Sleep"]]),
  A("as-y1-05", "The Cat Who Thought She Was a Dog", "🐱", 400, "Mimi was a cat. She had whiskers and a long tail. But Mimi thought she was a dog! She fetched sticks. She chased the postman. She went for walks on a lead. People stared. Then a dog called Bruno moved in next door. Bruno curled up in the sun and purred. Bruno thought he was a cat! They swapped jobs at once, and everyone was much happier.", "What did Bruno think he was?", [["🐱", "A cat"], ["🐶", "A dog"], ["🐟", "A fish"]]),
  A("as-y1-06", "Grandpa's Terrible Cooking", "🍳", 420, "Nobody liked Grandpa's cooking. His soup was gloopy. His cakes were as hard as bricks. One Sunday, he made a pizza. He put on cheese, jam, fish fingers and a whole banana! “A secret recipe,” he said. Nobody wanted to try it. So the dog did. He gobbled it up and wanted more! Now Grandpa makes Banana Fish Finger Pizza every Sunday. The dog eats it. Everyone else has toast.", "Who liked Grandpa's pizza?", [["🐶", "The dog"], ["👨‍👩‍👧", "Everyone"], ["👵", "Granny"]]),
  A("as-y1-07", "The Tooth Fairy's Day Off", "🧚", 440, "Lily put her tooth under her pillow. But the Tooth Fairy had a cold, so she sent her little brother, Dennis. Dennis bumped into the lamp. He fell into the goldfish bowl. Splash! Then he forgot why he had come. He took the tooth and left a sock! In the morning, Lily wrote a note. “Dear Tooth Fairy, I think there has been a mix-up.” The next night, there were two coins.", "What did Dennis leave under the pillow?", [["🧦", "A sock"], ["🪙", "A coin"], ["🍪", "A biscuit"]]),
  A("as-y1-08", "Sang Kancil and the Crocodiles", "🐊", 460, "Sang Kancil was a small mouse deer, but he was very clever. He wanted the fruit across the river. But the river was full of crocodiles! “The King wants to count you,” said Kancil. “Please line up!” The crocodiles lined up across the river. Kancil hopped on their backs. “One, two, three...” Hop, hop, hop! He reached the other side. “Thank you for the bridge!” he laughed.", "How did Kancil cross the river?", [["🐊", "On the crocodiles' backs"], ["🛶", "In a boat"], ["🏊", "He swam"]]),
  A("as-y1-09", "The Burp That Saved the Day", "💨", 490, "Toby did the biggest burps in school. “Manners, Toby!” said Mrs Prim. At the zoo, Mrs Prim's glasses fell onto a hippo's nose. The hippo opened its huge mouth! Then Toby drank his fizzy drink and burped. BUUURRRP! The hippo sneezed. The glasses flew back onto Mrs Prim's nose. Everyone cheered. Mrs Prim smiled. “Just this once, Toby,” she said.", "What made the hippo sneeze?", [["💨", "Toby's burp"], ["🌸", "A flower"], ["🐒", "A monkey"]]),
  A("as-y1-10", "The Moon Wants a Holiday", "🌙", 520, "The Moon was tired. “I want a holiday,” she said. So she floated down to the beach. She put on sunglasses and had an ice cream. But the sky was very dark. Owls bumped into trees. Cats fell off walls. A girl called Nora went to the beach. “Please come back,” she said. “We miss you.” So the Moon went back. Now she has one holiday a month.", "Who asked the Moon to come back?", [["👧", "Nora"], ["🦉", "An owl"], ["🐱", "A cat"]]),
];

const YEAR2: Passage[] = [
  A("as-y2-01", "The Day the Teacher Turned Into a Frog", "🐸", 480, "Mr Bunting, the strictest teacher at school, never smiled. One morning, someone put green powder in his tea. Puff! He turned into a frog wearing tiny glasses. Class 2B cheered. They ate crisps and painted the ceiling. But soon the room felt too quiet. Priya gave the frog a little kiss to say sorry. Puff! Mr Bunting was back, with pond weed in his hair. And, for the first time ever, he laughed.", "What did Priya do to turn the frog back?", [["💋", "Gave it a kiss"], ["🍵", "Gave it tea"], ["📚", "Read it a book"]]),
  A("as-y2-02", "Nenek's Secret Recipe", "🍛", 500, "Nenek made the best nasi lemak in Johor, with a secret ingredient. Aiman hid behind curtains to find it. He even hid in the rice sack, but he sneezed and got caught. “The secret,” whispered Nenek, “is that I cook for people I love.” The next Saturday, Aiman made a parcel for the grumpy man next door. The man took one bite and smiled. The secret worked!", "What was Nenek's secret ingredient?", [["❤️", "Cooking for people she loved"], ["🌶️", "Extra chilli"], ["🍯", "Honey"]]),
  A("as-y2-03", "Kevin the Rock", "🪨", 510, "Ruby's pet was a rock called Kevin. “Kevin can't do anything!” laughed Jack. On Pet Day, everything went wrong. The puppy chased the hamster. The parrot squawked. Then the wind blew the door open, and homework flew around the room like snow! Calmly, Ruby put Kevin on top of the pile. The papers stopped flying. Kevin won Pet of the Year. He looked very pleased.", "How did Kevin save the day?", [["📄", "He held the papers down"], ["🎵", "He played the piano"], ["🐶", "He caught the puppy"]]),
  A("as-y2-04", "Captain Cutlass and the Very Small Ship", "🏴‍☠️", 530, "Captain Cutlass was a fierce pirate, but his ship was really a bathtub with a sail. Other sailors laughed at him. One stormy night, a big ship sank. Its sailors could not swim! Captain Cutlass rowed out and pulled all seventeen into his bath. He took them safely home. They gave him a huge new ship as a thank-you. He gave it back. “Too big,” he said.", "What was Captain Cutlass's ship really?", [["🛁", "A bathtub"], ["🚢", "A huge ship"], ["🛶", "A canoe"]]),
  A("as-y2-05", "The Girl Who Never Stopped Asking Why", "❓", 550, "Ella asked “Why?” all day long. Her teacher started wearing earmuffs. One day, the whole town lost its power. “Why?” asked Ella. Nobody knew, so she went to find out. She followed the wires up the hill to the power station. Some squirrels had built a nest on the big switch! Ella moved it to a tree. Click! The lights came back on. The mayor gave her a medal.", "What had turned off the power?", [["🐿️", "A squirrels' nest"], ["⛈️", "A storm"], ["🐘", "An elephant"]]),
  A("as-y2-06", "Uncle Bernard's Bouncing Bed", "🛏️", 560, "Uncle Bernard bought the bounciest bed ever made. That night, he jumped into it. BOING! He shot up through the roof in his pyjamas, holding his teddy. He bounced over the church and the school. “Lovely evening!” he called to Mrs Patel. At last, he landed back on his bed and fell asleep. In the morning, he said he had dreamed of flying. Nobody mentioned the hole in the roof.", "Where did Uncle Bernard land at the end?", [["🛏️", "Back on his bed"], ["🌊", "In the river"], ["⛪", "On the church"]]),
  A("as-y2-07", "The Shy Dragon", "🐉", 580, "Fizz the dragon was very shy. When she blushed, smoke puffed out of her ears, and the villagers ran away screaming. One winter, the village ran out of firewood. A boy called Tomas climbed up to her cave. “Please help,” he said. “We're freezing.” Fizz gently breathed warm air over the village. The snow melted. The houses grew warm. Everyone cheered. Fizz blushed, but this time, she didn't mind.", "What happened when Fizz blushed?", [["💨", "Smoke came out of her ears"], ["🔥", "She breathed fire"], ["🌈", "She turned rainbow"]]),
  A("as-y2-08", "Mr Plum's Unusual Shop", "🏪", 590, "Mr Plum's strange shop sold things you didn't know you needed. He gave Leo a little brass key. “What does it open?” asked Leo. Mr Plum just smiled. The key did not open the front door. It did not open the biscuit tin. Then Leo's sister got locked in the bathroom! Leo tried the key. Click! The door opened. When Leo went back to say thank you, the shop had vanished.", "What did the brass key open?", [["🚪", "The bathroom door"], ["🍪", "The biscuit tin"], ["🚲", "His bike lock"]]),
  A("as-y2-09", "The Great Hamster Escape", "🐹", 600, "Every night, Nibbles the hamster practised his escape. On Friday, he picked the lock with a sunflower seed. He slid down the table leg and dived into the teacher's handbag. Inside, he ate mints and half a sandwich, then fell asleep. On Monday, Miss Hart reached for a pen and screamed! Out rolled Nibbles, with a mint on his ear. Now he is planning his next escape.", "Where did Nibbles hide?", [["👜", "In the teacher's handbag"], ["📚", "Behind the books"], ["🎒", "In a school bag"]]),
  A("as-y2-10", "Granny Goes to Space", "🚀", 610, "Granny Joan was ninety-two, and everyone said she was too old for space. So she built a rocket from a dustbin and a giant firework. She wore a goldfish bowl as a helmet. WHOOSH! She zoomed past the clouds and looped around the Moon. She even had tea with an astronaut. Then she landed in the vegetable patch. “Too old?” she said. “Next week, I'm going to Mars.”", "What did Granny use as a helmet?", [["🐠", "A goldfish bowl"], ["🪣", "A bucket"], ["🎩", "A top hat"]]),
];

const YEAR3: Passage[] = [
  A("as-y3-01", "The Boy Who Swallowed a Thunderstorm", "⛈️", 680, "One rainy afternoon, Felix Fennimore accidentally swallowed a small thundercloud. Whenever he got cross, he rumbled, and when he ate sprouts, it drizzled from his ears. Then a terrible drought came, and the village well dried up. Felix stood in the dusty fields, thought about every annoying thing that had ever happened to him, and roared. Out burst the storm! Rain poured down, and the farmers danced in the mud.", "How did Felix make the rain come?", [["😠", "He got very cross and roared"], ["💃", "He did a rain dance"], ["💧", "He used a hose"]]),
  A("as-y3-02", "Detective Dumpling and the Missing Mangoes", "🥭", 690, "Detective Dumpling, aged eight, was the only detective in Kampung Bunga. When Pak Ali's twelve mangoes vanished, she took the case. The goat had an alibi, and the postman was allergic to mangoes. Then she spotted mango peel on the bus stop, leading all the way to the jungle. Up in a tree sat a very fat, very happy monkey. It burped. Case solved. Her fee: one ripe mango.", "Who stole the mangoes?", [["🐒", "A monkey"], ["🐐", "Mrs Lim's goat"], ["📮", "The postman"]]),
  A("as-y3-03", "Barnaby Bland Is Extremely Ordinary", "😐", 700, "Barnaby Bland was the most ordinary boy in the world. Everyone else could juggle or wiggle their ears. At the talent show, the lights suddenly went out, and the class guinea pig escaped. Everybody panicked, and somebody's grandad got stuck in the curtains. But Barnaby stayed calm. He switched on his torch and found the guinea pig under the piano. Staying calm, it turns out, is an extraordinary talent.", "What was Barnaby's special talent?", [["😌", "Staying calm"], ["🤹", "Juggling"], ["🦖", "Naming dinosaurs"]]),
  A("as-y3-04", "Penelope Pott's Perfectly Dreadful Party", "🎂", 710, "Penelope Pott planned the perfect party. Rule one was: NOTHING WILL GO WRONG. Then the magician turned his rabbit into a grapefruit, the chocolate fountain exploded, and the dog ate the castle cake. Penelope burst into tears. But outside, her friends were laughing, having a chocolate water fight. So she tore out rule one and joined in. It was the best party anybody could remember.", "What happened to the castle cake?", [["🐶", "The dog ate it"], ["🔥", "It burned"], ["🎩", "The magician took it"]]),
  A("as-y3-05", "The Library at the Bottom of the Sea", "🐙", 720, "While snorkelling, Marina spotted a light deep beneath the bay. She dived down and found a stone door marked: THE SUNKEN LIBRARY. NO SPLASHING. The librarian was an elderly octopus wearing four pairs of spectacles. Marina read all afternoon, from pirate diaries to a cross lobster's cookbook. She borrowed one silver book. It is still on her shelf, and if you open it, you can hear the sea.", "Who was the librarian?", [["🐙", "An octopus"], ["🦀", "A crab"], ["🐋", "A whale"]]),
  A("as-y3-06", "Mrs Mangle's Magnificent Moustache", "👵", 730, "Nobody knew why Mrs Mangle, the baker, grew a moustache. By Friday, it was long enough to tuck into her apron. At the Great Bake-Off, she carried out an enormous, wobbly cake. Suddenly, the top layer began to slide! Quick as a flash, she flicked her moustache underneath and held it perfectly in place. She won first prize. “You never know when you'll need one,” she said.", "How did Mrs Mangle save her cake?", [["👨", "With her moustache"], ["🥄", "With a big spoon"], ["🧤", "With oven gloves"]]),
  A("as-y3-07", "The Robot Who Wanted to Be a Chicken", "🤖", 740, "Unit X-9000 was the cleverest robot ever built. It could speak forty languages and build bridges. But it did not want to. It wanted to be a chicken. So Professor Gearbox took it to a farm. It learned to strut and peck, and it made feathers from tin foil. It never laid an egg. But it designed the world's best henhouse, with a disco ball. The hens were delighted.", "What did the robot design for the hens?", [["🏠", "The best henhouse in the world"], ["🌉", "A bridge"], ["🚀", "A rocket"]]),
  A("as-y3-08", "The Night the Toys Went on Strike", "🧸", 760, "Maisie was not kind to her toys. She left her teddy, Captain Buttons, out in the rain and drew a moustache on her doll. So one night, the toys went on strike. In the morning, Maisie found them in the garden shed, holding signs that said: WE WANT RESPECT. Maisie felt ashamed. She said sorry to every toy and carried them home. That night, Captain Buttons winked.", "Where did Maisie find her toys?", [["🛖", "In the garden shed"], ["🛏️", "Under the bed"], ["📦", "In the attic"]]),
  A("as-y3-09", "Granny's Great Gorilla Mix-Up", "🦍", 780, "Granny Pearl ordered a fluffy brown rug online, but she clicked the wrong button. A fluffy brown gorilla called Gordon arrived instead. Granny was short-sighted, so she stood on him to reach the top shelf. Gordon was too polite to complain. When her grandson saw the rug yawn, he screamed. But Granny refused to let Gordon go. “He does the gardening,” she said, “and he's an excellent listener.”", "What did Granny Pearl think Gordon was?", [["🟫", "A rug"], ["🧸", "A teddy"], ["🐻", "A bear"]]),
  A("as-y3-10", "The Kite That Flew Away With Mr Tan", "🪁", 800, "For fifty years, Mr Tan had flown kites every Sunday. This year, he built one as big as a bus. “Too big,” warned his wife. He let it go, and the wind lifted him right off the sand! He floated over a fishing boat, and some monkeys threw a banana at him. An hour later, he landed beside his wife's deckchair. “Too big?” she asked. “Perhaps,” he admitted.", "What did the monkeys throw at Mr Tan?", [["🍌", "A banana"], ["🥥", "A coconut"], ["🪨", "A stone"]]),
];

const YEAR4: Passage[] = [
  A("as-y4-01", "The Headmaster Who Hated Noise", "🤫", 790, "Dr Hushworth, the headmaster, hated noise so much that sneezing required written permission. Then Amira arrived, with the loudest laugh in the world. In silent assembly, she noticed spinach stuck in his teeth. Her laugh exploded: “HA-HA-HONK!” Soon, three hundred children were howling on the floor. Dr Hushworth turned purple, then began to laugh too. Now the whole school laughs together every Friday, led by Amira.", "What made Amira laugh in assembly?", [["🥬", "Spinach in the headmaster's teeth"], ["🤡", "A clown"], ["🐦", "A bird in the hall"]]),
  A("as-y4-02", "The Secret Diary of a Very Nervous Lighthouse", "🗼", 800, "Monday: I am Lumi, a lighthouse who is afraid of the dark. Embarrassing, I know. Tuesday: During the storm, I pretended to be a very tall tree. Thursday: Through the fog, I saw a little boat heading for the rocks. I was trembling, but I thought, how frightened must that girl be? So I shone brighter than ever. She was saved. Friday: Being brave means shining anyway.", "What was Lumi the lighthouse scared of?", [["🌑", "The dark"], ["🌊", "Big waves"], ["🐦", "Seagulls"]]),
  A("as-y4-03", "The Great Grandad Swap", "👴", 810, "Oliver thought his crossword-loving grandad was boring. Jaya's grandpa made her jog at dawn and played the bagpipes in the bath. So they swapped grandads for half-term. By Tuesday, Oliver was exhausted, and Jaya was bored silly. They swapped back, missing their own grandads. Then the two grandads met and became friends. Now they jog together every Saturday, very slowly, and finish with a crossword.", "What did Jaya's grandpa play in the bath?", [["🎶", "The bagpipes"], ["🎸", "The guitar"], ["🥁", "The drums"]]),
  A("as-y4-04", "The Ghost Who Was Afraid of Children", "👻", 820, "For three hundred years, Lady Wimbledon's ghost had terrified everyone at Grimthorpe Castle. Then a family with five fearless children moved in. When she rattled her chains, they made a swing out of them. When she floated past carrying her own head, little Hattie asked to hold it. Eventually, Hattie handed her a book. “Read us a story,” she said. Now Lady Wimbledon reads bedtime stories every night.", "What did the children ask Lady Wimbledon to do?", [["📖", "Read them a story"], ["⛓️", "Rattle her chains"], ["🏰", "Leave the castle"]]),
  A("as-y4-05", "The Inventor of Useless Things", "💡", 830, "Professor Ida Bloom invented useless things, like a sock matcher that ate socks and umbrellas for ducks. Everybody laughed at her. Then a great flood swept through the town, and the water pumps broke. The desperate mayor paddled to her window for help. She switched her sock matcher to WATER, and it slurped up the whole flood overnight. The newspapers renamed her “the Inventor of Things We Didn't Know We Needed.”", "What did the Sock Matcher do in the flood?", [["💧", "It sucked up the water"], ["🧦", "It ate socks"], ["🍲", "It made soup"]]),
  A("as-y4-06", "The Night Market Mystery", "🏮", 840, "Every Wednesday at nine o'clock, the lights at the pasar malam went out, and food vanished: pisang goreng, chicken wings, even a pot of laksa. People blamed a ghost. Siti hid under a stall with a torch. When the lights failed, she spotted a monitor lizard carrying away a tray of banana fritters. She followed it to a drain, where six hungry babies were waiting. The thief was just a mother shopping.", "Who was stealing the food?", [["🦎", "A mother monitor lizard"], ["👻", "A ghost"], ["👦", "Teenagers"]]),
  A("as-y4-07", "The Boy Who Could Talk to Pigeons", "🐦", 850, "After swallowing a feather, Sam could understand pigeons. Unfortunately, pigeons never stopped arguing about crumbs. Then the mayor's dog went missing, and the whole city searched for days. Sam overheard two pigeons gossiping: the dog was stuck in a drainpipe by the river. Sam rescued him. As a reward, he asked only for a bag of bread for the pigeons. Now they bow when he passes.", "Where was the missing dog?", [["🌉", "In a drainpipe by the river"], ["🏞️", "In the park"], ["🏠", "On a roof"]]),
  A("as-y4-08", "The Queen of the Supermarket", "🛒", 860, "Mrs Fairweather had been a supermarket cashier for forty-two years and knew every price by heart. One Saturday, the computers crashed, trapping two hundred shoppers inside. The manager panicked. “Form an orderly queue, my darlings,” said Mrs Fairweather calmly. She added up every trolley in her head, writing totals on a paper bag. Today, that bag hangs in a golden frame above the tills: IN CASE OF EMERGENCY, ASK THE QUEEN.", "How did Mrs Fairweather add up the shopping?", [["🧠", "In her head"], ["💻", "On a computer"], ["🧮", "With a calculator"]]),
  A("as-y4-09", "The Elephant Who Forgot", "🐘", 860, "Mabel was an elephant who forgot everything, even where her trunk was. The herd sighed. Then a drought came, and old Grandmother Tembo couldn't remember the way to the secret spring. But because Mabel never remembered anything, she looked carefully at everything. She had noticed birds flying north and returning with wet feathers. “Follow the birds!” she trumpeted. They found the spring. Forgetting, it seemed, had taught her to notice.", "What helped Mabel find the spring?", [["🐦", "She followed the birds"], ["🗺️", "She used a map"], ["🧠", "She remembered the way"]]),
  A("as-y4-10", "Operation Cheese Toastie", "🧀", 870, "At midnight, Agents Mia and Leo crept downstairs on a dangerous mission: to make a cheese toastie without waking their parents. They stepped over the creaky floorboard and slid down the banister. The toastie sizzled perfectly. Then the smoke alarm went off! BEEP! BEEP! Mum and Dad appeared in their dressing gowns. There was a long silence. “Is there enough cheese for four?” asked Dad. It became a family tradition.", "What woke up Mum and Dad?", [["🚨", "The smoke alarm"], ["🐶", "The dog"], ["🪵", "The creaky floorboard"]]),
];

const YEAR5: Passage[] = [
  A("as-y5-01", "The Boy Who Was Allergic to Adventure", "🗺️", 900, "Horace Plimpton was genuinely allergic to adventure: anything exciting gave him purple spots. Then his great-aunt left him a map and a note: “The cure is at the X.” Horace set off, sneezing, and was chased by geese and lost in a maze. At the X, on a hilltop, he found only a bench carved with the words: “The cure is to keep going.” His spots faded completely.", "What was the cure for Horace's allergy?", [["🚶", "To keep going"], ["💊", "A special medicine"], ["💰", "Finding treasure"]]),
  A("as-y5-02", "The Substitute Teacher From the Year 3000", "🛸", 910, "The substitute teacher, Ms Zyx, wore silver boots, ate her yoghurt pot and seemed astonished by pencils. Kofi confronted her: “You're from the future.” She admitted it. She was a historian from the year 3000, studying a real classroom. “In my time, machines entertain everyone constantly,” she explained, “so nobody is ever bored, and nobody imagines anything new.” She left a note: “Thank you for the boredom.”", "Why did Ms Zyx visit the past?", [["📚", "To study a real classroom"], ["🍦", "To eat yoghurt"], ["🔭", "To see the Sun"]]),
  A("as-y5-03", "The Durian Tree That Wouldn't Share", "🌳", 920, "Encik Kamal owned the finest durian tree in Malaysia, but he fenced it in and refused to share a single fruit. One year, the tree stopped fruiting altogether. “Perhaps it's lonely,” suggested little Nurul. That night, sitting alone beneath its empty branches, Encik Kamal understood. He tore down the fences and put up a sign: EVERYONE WELCOME. Within a week, the branches were heavy with durians.", "What made the durian tree fruit again?", [["🤝", "Sharing it with everyone"], ["🧪", "Expensive powder"], ["📜", "A lawyer's letter"]]),
  A("as-y5-04", "Agatha Grimwhistle and the Disappearing Spelling Test", "📝", 930, "For three Fridays running, the spelling test vanished from Mr Crumb's desk. Agatha Grimwhistle, who actually enjoyed spelling tests, investigated. Freddie had an alibi, and the caretaker's bin bag held only leaves. So she hid in the stationery cupboard after school. At half past four, Archimedes the tortoise plodded across the desk and began nibbling the envelope. He loved the glue. Mr Crumb switched to white envelopes.", "Who was taking the spelling tests?", [["🐢", "Archimedes the tortoise"], ["🧹", "Mr Mopps the caretaker"], ["👦", "Freddie Fotheringham"]]),
  A("as-y5-05", "The Last Dragon in Kuala Lumpur", "🐉", 940, "On a skyscraper in Kuala Lumpur lived a secret dragon, Seri Naga, known only to Mei Ling. “Where are the other dragons?” Mei Ling asked. “When the forests shrink,” said Seri Naga sadly, “dragons fall asleep.” So Mei Ling started a club where every member planted a tree. When the half-millionth tree was planted, deep in the rainforest, an ancient dragon opened one golden eye. The dragons were waking up.", "What did members of the Dragon Keepers have to do?", [["🌱", "Plant a tree"], ["🐉", "Find a dragon"], ["🍵", "Make teh tarik"]]),
  A("as-y5-06", "The Sweet Shop Owner Who Hated Children", "🍬", 950, "Mr Grimsby owned a wonderful sweet shop, yet he despised children. His parrot even screeched “Hurry up!” at customers. One evening, a girl with holes in her shoes placed a single coin on the counter. “It's my poorly brother's birthday,” she said. Something in Mr Grimsby's chest creaked. He filled a bag with sweets and pushed the coin back. The next day, his sign read: FREE SAMPLES ON FRIDAYS.", "What did Mr Grimsby give the girl?", [["🍭", "A bag full of sweets, and her coin back"], ["🧥", "A new coat"], ["🦜", "His parrot"]]),
  A("as-y5-07", "The World's Worst Superhero", "🦸", 960, "On his eleventh birthday, Archie got superpowers, but they were hopeless: he could fly two centimetres high and only see through sandwiches. Then thieves stole a priceless diamond from the museum, and the police couldn't find it anywhere. Archie squinted at the leader's lunchbox. “It's in the sandwich!” he shouted. He hovered just high enough to trip the fleeing thief. Newspapers called him SANDWICH BOY.", "Where was the diamond hidden?", [["🥪", "In a sandwich"], ["🧥", "In a coat pocket"], ["🎒", "In a school bag"]]),
  A("as-y5-08", "The Girl Who Collected Lost Things", "🧤", 970, "Wren collected lost things and tried to return them. Her greatest puzzle was an unsent love letter, fifty years old, from “E” to Margaret, who lived in a house with a blue door. Every door had since been repainted. Then Wren noticed an old woman with a sailor's photograph on her windowsill. It was Margaret. Edward was still alive. Wren was guest of honour at their wedding.", "Who was the love letter for?", [["👵", "Margaret"], ["👨‍✈️", "A sea captain"], ["👶", "A toddler"]]),
  A("as-y5-09", "The Cat Who Ran the Country", "🐈", 980, "Nobody knew how Tiddles, a fat ginger cat, became Prime Minister. His first law made afternoon naps compulsory. His second reserved all cardboard boxes for sitting in. His third banned the hoover. Surprisingly, people grew calmer, children built cardboard rockets, and families spent weekends together. The country became the happiest it had been for a century. Tiddles served one term, then fell asleep in a sunbeam.", "What did Tiddles' first law make compulsory?", [["😴", "Afternoon naps"], ["📦", "Sitting in boxes"], ["🧹", "Hoovering"]]),
  A("as-y5-10", "The Orchestra of Unwanted Instruments", "🎻", 990, "Beneath the Grand Theatre lay forgotten instruments: a dented trumpet, a three-string violin and a hopelessly out-of-tune piano. Ottilie discovered them and composed a strange, joyful tune. On opening night, a storm damaged the orchestra's shiny new instruments. Then, from under the stage, came a squashed trumpet note. Ottilie led musicians up the stairs by candlelight, carrying the unwanted instruments. Critics called the concert “imperfectly perfect”.", "What happened to the orchestra's new instruments?", [["⛈️", "They were damaged in the storm"], ["🎁", "They were sold"], ["🕵️", "They were stolen"]]),
];

const YEAR6: Passage[] = [
  A("as-y6-01", "The Boy Who Sold His Shadow", "🌑", 960, "Jasper sold his shadow to a stranger for a hundred pounds and bought a bicycle. Soon, however, he began forgetting things: his grandmother's laugh, the smell of the sea. Desperate, he found the stranger's shop, lined with rolled-up shadows. Instead of paying, Jasper walked into the sunlight, deliberately remembering every precious detail. With each memory, his shadow darkened again. The stranger could only keep what you surrendered.", "How did Jasper get his shadow back?", [["🧠", "By holding on to his memories"], ["💰", "By paying the stranger"], ["✂️", "By cutting it out"]]),
  A("as-y6-02", "The Last Bookshop on Jalan Merdeka", "📚", 970, "Mr Rahman's struggling bookshop on Jalan Merdeka was to be demolished for a car park. His granddaughter Aisyah fought back, posting witty book reviews online until thousands of customers arrived. On demolition morning, hundreds of people filled the street, silently reading together. The bulldozer driver switched off his engine and went inside to buy a book about tigers. The plans were withdrawn. Stories, Aisyah wrote, are louder than bulldozers.", "What did the crowd do on the last morning?", [["📖", "Read books silently together"], ["📢", "Shouted and protested"], ["🎶", "Sang songs"]]),
  A("as-y6-03", "The Unusual Inheritance of Florence Fairbottom", "🏰", 980, "Florence inherited a crumbling Scottish castle and a curse: keep the castle's promise, or it falls into the sea. Nobody remembered the promise. Exploring, she discovered the first Lady's diary hidden behind a portrait. Centuries earlier, the castle had promised to keep a light burning for anyone lost at sea. That night, Florence climbed the highest tower and lit a lantern. The cracks in the walls stopped spreading.", "What was the castle's promise?", [["🕯️", "To keep a light burning for anyone lost at sea"], ["💰", "To guard a treasure"], ["🦇", "To protect the bats"]]),
  A("as-y6-04", "The Day Everyone Told the Truth", "🤥", 990, "One March morning, something in the water made everyone in Little Fibbington incapable of lying. Chaos erupted: Mr Henderson admitted that his wife's porridge tasted like wallpaper paste. Yet by afternoon, people began confessing kinder truths. A grumpy postman told an old lady that her waving brightened his day, and estranged brothers forgot their argument. Now the town celebrates Truth Day, when everyone says one true, kind thing.", "What good thing happened after the chaos?", [["💬", "People said kind, true things"], ["🏊", "The pool opened"], ["🥣", "The porridge got better"]]),
  A("as-y6-05", "Letters to the Future", "✉️", 1000, "For the school time capsule, ten-year-old Leo wrote about his grandmother, a nurse who was seriously ill. He ended with a question: “Was she remembered?” Fifty years later, Amara read the letter aloud while Leo, now white-haired, sat listening. She stepped away from the microphone. “The hospital's children's ward is named after Grace Okafor,” she told him gently. “She was remembered.” Together, they wrote a new letter.", "Who was Leo's letter about?", [["👵", "His grandmother"], ["⚽", "His football team"], ["🐶", "His pet"]]),
  A("as-y6-06", "The Kingdom of Lost Socks", "🧦", 1000, "Imogen fell through her broken washing machine into a cavern where millions of escaped socks had built a kingdom. Their king, an ancient Christmas sock, declared they were free from smelly trainers forever. But Imogen noticed that many socks looked homesick. So she negotiated a treaty: gentle washing, sunshine drying, and partners of their choice. Since then, missing socks have decreased dramatically, though some still take holidays.", "What did Imogen agree with the King of the socks?", [["📜", "A treaty"], ["🧺", "A new washing machine"], ["🎉", "A party"]]),
  A("as-y6-07", "The Clockmaker's Apprentice", "⏰", 1010, "In the back room of his shop, Master Horologe kept a clock that hadn't ticked for a century. When the old clockmaker fell ill, his apprentice, Pip, finally lifted its dust sheet. Its brass plate read: THE HEART OF TICKLETHWAITE. Working all night, she repaired it. As it began ticking, the town transformed: rivers sparkled, gardens bloomed, and upstairs, her master's cough vanished completely.", "What happened when the great clock ticked again?", [["🌸", "The town came back to life"], ["🌧️", "It began to rain"], ["🔔", "All the bells rang"]]),
  A("as-y6-08", "The Silent Football Match", "⚽", 1020, "Three days before the cup final, Kwame, the team's best striker, lost his hearing after an illness. Danny devised a plan: the team learned silent signals, like a raised fist meaning “pass”. On match day, they played without a single shout, despite their noisy opponents. Ten minutes from the end, Danny raised his fist. Kwame scored. His teammates surrounded him, each placing a hand on his chest: well done.", "How did the team talk to Kwame during the match?", [["🤚", "With hand signals"], ["📢", "By shouting"], ["📱", "With phones"]]),
  A("as-y6-09", "Grandfather's Impossible Garden", "🌻", 1030, "Grandfather's tiny Manchester garden grew impossible mangoes and pineapples, baffling university scientists. When he fell ill, the plants began dying, and no heat lamps could save them. His granddaughter Chidinma remembered how he talked and sang to them every morning. So she did the same, telling them stories and singing his song. By spring, everything flourished. “You found the secret,” Grandfather smiled when he returned.", "What was the secret of the garden?", [["🗣️", "Talking and singing to the plants"], ["💡", "Heat lamps"], ["🧪", "Special fertiliser"]]),
  A("as-y6-10", "The Map That Drew Itself", "🗺️", 1040, "In her grandmother's dusty attic, Isla discovered a blank map that inked itself wherever she walked. Curious, she followed its wandering lines through a secret door hidden in the hedge. Beyond lay a forgotten kingdom of talking foxes and floating lanterns, frozen beneath an ancient enchantment. “Only someone who finishes the map can wake us,” whispered an elderly fox. Isla walked until dawn. As the final line appeared, the entire kingdom yawned awake.", "What happened to the map as Isla walked?", [["🖋️", "It drew itself"], ["🔥", "It burned"], ["🦊", "A fox stole it"]]),
];

const BY_LEVEL: Record<string, Passage[]> = {
  starter: STARTER,
  year1: YEAR1,
  year2: YEAR2,
  year3: YEAR3,
  year4: YEAR4,
  year5: YEAR5,
  year6: YEAR6,
};

/** The assignment stories for a reading level ([] if it has none). */
export function assignmentStories(levelId: string): Passage[] {
  return BY_LEVEL[levelId] ?? [];
}

/** One assignment story by id, wherever it's filed. */
export function findAssignmentStory(id: string): Passage | null {
  for (const list of Object.values(BY_LEVEL)) {
    const hit = list.find((p) => p.id === id);
    if (hit) return hit;
  }
  return null;
}

/** A child's assignment story and its level: one of these stories, or (for a
    story set before they existed) a Guided Reading passage. */
export function storyFor(storyId: string, levelId: string): { passage: Passage; level: PassageLevel } | null {
  const passage = findAssignmentStory(storyId);
  const level = passageLevels.find((l) => l.id === levelId);
  if (passage && level) return { passage, level };
  return findPassage(storyId, levelId);
}
